import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { assessNeed, rankFacilities, type Assessment, type Facility } from "@ruralcare/shared";
import "./styles.css";

type Referral = { id: string; patientLabel: string; sourceFacility: string; destinationFacility: string; service: string; urgency: string; status: string; nextAction: string; createdAt: string };
const localFacilities: Facility[] = [
  { id: "aam-kallur", name: "Kallur Ayushman Arogya Mandir", type: "AAM", distanceKm: 1.8, services: ["PRIMARY_CARE", "CHILD_HEALTH", "TELECONSULT"], available: true, hours: "Mon-Sat, 9:00-16:00", address: "Kallur village (synthetic)", phone: "00000 00001", latitude: 11.01, longitude: 78.01 },
  { id: "phc-melur", name: "Melur Public Health Centre", type: "PHC", distanceKm: 5.6, services: ["PRIMARY_CARE", "CHILD_HEALTH", "MATERNITY", "TELECONSULT"], available: true, hours: "24x7 maternity; OPD 9:00-17:00", address: "Melur block (synthetic)", phone: "00000 00002", latitude: 11.04, longitude: 78.05 },
  { id: "chc-vadakku", name: "Vadakku Community Health Centre", type: "CHC", distanceKm: 14.2, services: ["PRIMARY_CARE", "CHILD_HEALTH", "MATERNITY", "EMERGENCY"], available: true, hours: "24x7 emergency", address: "Vadakku town (synthetic)", phone: "00000 00003", latitude: 11.12, longitude: 78.11 },
  { id: "dh-demo", name: "District Government Hospital", type: "DISTRICT_HOSPITAL", distanceKm: 27.5, services: ["PRIMARY_CARE", "CHILD_HEALTH", "MATERNITY", "EMERGENCY"], available: true, hours: "24x7", address: "Demo district HQ (synthetic)", phone: "00000 00004", latitude: 11.24, longitude: 78.2 }
];
const queueKey = "ruralcare-referral-queue";
function queueReferral(data: unknown) { const queue = JSON.parse(localStorage.getItem(queueKey) || "[]"); queue.push(data); localStorage.setItem(queueKey, JSON.stringify(queue)); }
async function request(path: string, init?: RequestInit) { const response = await fetch(path, { headers: { "Content-Type": "application/json" }, ...init }); if (!response.ok) throw new Error("Network unavailable"); return response.json(); }

function App() {
  const [language, setLanguage] = useState<"en" | "ta">("en"); const [view, setView] = useState<"intake" | "assessment" | "facilities" | "referral" | "followup" | "dashboard">("intake");
  const [message, setMessage] = useState(""); const [assessment, setAssessment] = useState<Assessment | null>(null); const [facilities, setFacilities] = useState<Facility[]>([]); const [selected, setSelected] = useState<Facility | null>(null); const [patientLabel, setPatientLabel] = useState("Demo patient"); const [notice, setNotice] = useState(""); const [online, setOnline] = useState(navigator.onLine); const [dashboard, setDashboard] = useState<{ referrals: Referral[]; totals: { total: number; urgent: number; pending: number }; demand: { service: string; count: number }[] } | null>(null);
  const labels = useMemo(() => language === "ta" ? { title: "ரூரல்கேர் கனெக்ட்", subtitle: "உங்கள் தேவைக்கு சரியான பொது சுகாதார சேவையை கண்டறிய உதவுகிறது", prompt: "உங்களுக்கு என்ன உதவி தேவை?", continue: "தொடரவும்", staff: "பணியாளர் பலகை" } : { title: "RuralCare Connect", subtitle: "Find an appropriate public healthcare service", prompt: "Tell us what you need help with", continue: "Continue safely", staff: "Staff dashboard" }, [language]);
  useEffect(() => { const on = () => setOnline(true); const off = () => setOnline(false); addEventListener("online", on); addEventListener("offline", off); return () => { removeEventListener("online", on); removeEventListener("offline", off); }; }, []);
  useEffect(() => { if (!online) return; const queued = JSON.parse(localStorage.getItem(queueKey) || "[]"); if (!queued.length) return; Promise.all(queued.map((item: unknown) => request("/api/referrals", { method: "POST", body: JSON.stringify(item) }))).then(() => { localStorage.removeItem(queueKey); setNotice("Queued referral synced successfully."); }).catch(() => undefined); }, [online]);
  async function triage() { if (!message.trim()) return setNotice("Please describe the need first."); const local = assessNeed(message); setAssessment(local); setView("assessment"); try { const result = await request("/api/triage", { method: "POST", body: JSON.stringify({ message }) }); setAssessment(result.assessment); } catch { setNotice("Offline safety fallback is active."); } }
  async function findFacilities() { if (!assessment) return; const fallback = rankFacilities(localFacilities, assessment.service); setFacilities(fallback); setView("facilities"); try { const result = await request(`/api/facilities?service=${assessment.service}`); setFacilities(result.facilities); } catch { setNotice("Showing verified-for-demo cached facility data. Verify before travel."); } }
  async function createReferral() { if (!selected || !assessment) return; const body = { patientLabel, sourceFacility: "ASHA-assisted intake", destinationFacility: selected.name, service: assessment.service, urgency: assessment.urgency, nextAction: assessment.nextAction }; try { const result = await request("/api/referrals", { method: "POST", body: JSON.stringify(body) }); setNotice(`Referral ${result.referral.id.slice(-6)} created. Follow-up is due tomorrow.`); } catch { queueReferral(body); setNotice("Offline: referral saved on this device and will sync when online."); } setView("followup"); }
  async function openDashboard() { setView("dashboard"); try { setDashboard(await request("/api/dashboard")); } catch { setNotice("Dashboard needs a connection to load live demo activity."); } }
  function startVoice() { const Speech = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Speech) return setNotice("Voice input is unavailable in this browser. Please type your need."); const recognition = new Speech(); recognition.lang = language === "ta" ? "ta-IN" : "en-IN"; recognition.onresult = (event: any) => setMessage(event.results[0][0].transcript); recognition.start(); }
  return <main><header><div><p className="eyebrow">SIH26133 • SYNTHETIC PROTOTYPE</p><h1>{labels.title}</h1><p>{labels.subtitle}</p></div><div className="header-actions"><button className="plain" onClick={() => setLanguage(language === "en" ? "ta" : "en")}>{language === "en" ? "தமிழ்" : "English"}</button><button className="plain" onClick={openDashboard}>{labels.staff}</button></div></header><div className="safety"><strong>Prototype safety:</strong> Not medical diagnosis. Synthetic data only. Verify facility availability before travel. <span className={online ? "online" : "offline"}>{online ? "● Online" : "● Offline"}</span></div>{notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}
  {view === "intake" && <section className="card hero"><span className="icon">✚</span><h2>{labels.prompt}</h2><p>Type in Tamil, English, or both. An ASHA worker can assist you.</p><textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder={language === "ta" ? "உதாரணம்: குழந்தைக்கு காய்ச்சல் உள்ளது" : "Example: My child has fever and cough for two days"}/><div className="actions"><button className="secondary" onClick={startVoice}>🎙 Voice input</button><button onClick={triage}>{labels.continue} →</button></div><p className="small">Voice is optional. The safety flow works with typed input and offline fallback.</p></section>}
  {view === "assessment" && assessment && <section className="card"><p className="eyebrow">STEP 2 OF 5 • CONFIRM UNDERSTANDING</p><h2>{assessment.urgency === "EMERGENCY" ? "Emergency guidance" : "What we understood"}</h2><div className={`urgency ${assessment.urgency.toLowerCase()}`}><strong>{assessment.urgency}</strong><span>{assessment.nextAction}</span></div><dl><dt>Service needed</dt><dd>{assessment.service.replaceAll("_", " ")}</dd><dt>Language detected</dt><dd>{assessment.language}</dd><dt>Possible concerns</dt><dd>{assessment.symptoms.join(", ")}</dd></dl><p>{assessment.explanation}</p>{assessment.urgency === "EMERGENCY" ? <><button onClick={() => setNotice("Demo SMS alert prepared for the appropriate emergency contact.")}>Simulate SMS emergency alert</button><button className="secondary" onClick={() => setView("intake")}>Start again</button></> : <div className="actions"><button className="secondary" onClick={() => setView("intake")}>Edit request</button><button onClick={findFacilities}>Confirm and find public care →</button></div>}</section>}
  {view === "facilities" && assessment && <section><p className="eyebrow">STEP 3 OF 5 • PUBLIC FACILITIES</p><h2>Suitable services near you</h2><p>Ranked by service capability, mock availability, and distance—not distance alone.</p><div className="grid">{facilities.map((facility) => <article className="facility" key={facility.id}><div><span className="tag">{facility.type}</span><span className="distance">{facility.distanceKm} km</span></div><h3>{facility.name}</h3><p>{facility.address}</p><p><strong>Why recommended:</strong> Offers {assessment.service.replaceAll("_", " ")} and is marked available in this prototype.</p><p className="small">{facility.hours}</p><button onClick={() => { setSelected(facility); setView("referral"); }}>Choose facility →</button></article>)}</div><button className="secondary" onClick={() => setView("assessment")}>← Back</button></section>}
  {view === "referral" && selected && assessment && <section className="card"><p className="eyebrow">STEP 4 OF 5 • REFERRAL CONTINUITY</p><h2>Referral to {selected.name}</h2><label>Patient label (demo only)<input value={patientLabel} onChange={(e) => setPatientLabel(e.target.value)} maxLength={40}/></label><div className="referral-summary"><strong>Summary</strong><p>Service: {assessment.service.replaceAll("_", " ")} · Urgency: {assessment.urgency}</p><p>Next action: {assessment.nextAction}</p><p>Destination: {selected.name}, {selected.distanceKm} km · {selected.hours}</p></div><div className="actions"><button className="secondary" onClick={() => setView("facilities")}>Choose another</button><button onClick={createReferral}>Create referral & follow-up →</button></div></section>}
  {view === "followup" && <section className="card"><p className="eyebrow">STEP 5 OF 5 • FOLLOW-UP</p><h2>Your next step is saved</h2><div className="timeline"><div><b>Today</b><span>Referral created or safely queued on this device.</span></div><div><b>Tomorrow</b><span>Follow-up reminder: confirm that the public facility was reached.</span></div></div><button onClick={() => { setView("intake"); setMessage(""); setAssessment(null); setSelected(null); }}>Start a new assisted journey</button></section>}
  {view === "dashboard" && <section><p className="eyebrow">STAFF VIEW • SYNTHETIC, NON-IDENTIFYING DATA</p><h2>Referral coordination dashboard</h2>{dashboard ? <><div className="metrics"><div><b>{dashboard.totals.total}</b><span>Total referrals</span></div><div><b>{dashboard.totals.urgent}</b><span>Urgent / emergency</span></div><div><b>{dashboard.totals.pending}</b><span>Pending follow-up</span></div></div><div className="grid"><article className="facility"><h3>Demand signals</h3>{dashboard.demand.map((d) => <p key={d.service}>{d.service}<strong className="right">{d.count}</strong></p>)}</article><article className="facility"><h3>Recent referrals</h3>{dashboard.referrals.length ? dashboard.referrals.map((r) => <p key={r.id}><strong>{r.patientLabel}</strong><br/>{r.destinationFacility}<br/><span className="tag">{r.status}</span></p>) : <p>No submitted referrals yet. Complete the citizen journey to create one.</p>}</article></div></> : <p>Loading local coordination data…</p>}<button className="secondary" onClick={() => setView("intake")}>← Citizen flow</button></section>}</main>;
}
declare global { interface Window { SpeechRecognition?: any; webkitSpeechRecognition?: any; } }
createRoot(document.getElementById("root")!).render(<App/>);
