import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { AlertTriangle, ArrowRight, BadgeCheck, CalendarDays, ChevronLeft, ClipboardPlus, CloudOff, HeartPulse, Languages, MapPin, Mic, Navigation, PhoneCall, ShieldCheck, Sparkles, Stethoscope, UsersRound, Wifi, type LucideIcon } from "lucide-react";
import { assessNeed, rankFacilities, type Assessment, type Facility } from "@ruralcare/shared";
import "./styles.css";

type View = "intake" | "assessment" | "facilities" | "referral" | "followup" | "dashboard";
type Referral = { id: string; patientLabel: string; destinationFacility: string; urgency: string; status: string; createdAt: string };
const scenarios = [
  { label: "Child fever", tamil: "குழந்தைக்கு காய்ச்சல்", message: "My child has fever and cough for two days", Icon: HeartPulse },
  { label: "Pregnancy care", tamil: "கர்ப்ப கால பராமரிப்பு", message: "I am pregnant and need a check-up", Icon: CalendarDays },
  { label: "General check-up", tamil: "பொது பரிசோதனை", message: "I need a general health check-up", Icon: Stethoscope }
];
const localFacilities: Facility[] = [
  { id: "aam-kallur", name: "Kallur Ayushman Arogya Mandir", type: "AAM", distanceKm: 1.8, services: ["PRIMARY_CARE", "CHILD_HEALTH", "TELECONSULT"], available: true, hours: "Mon-Sat · 9:00-16:00", address: "Kallur village (synthetic)", phone: "00000 00001", latitude: 11.01, longitude: 78.01 },
  { id: "phc-melur", name: "Melur Public Health Centre", type: "PHC", distanceKm: 5.6, services: ["PRIMARY_CARE", "CHILD_HEALTH", "MATERNITY", "TELECONSULT"], available: true, hours: "24x7 maternity · OPD 9:00-17:00", address: "Melur block (synthetic)", phone: "00000 00002", latitude: 11.04, longitude: 78.05 },
  { id: "chc-vadakku", name: "Vadakku Community Health Centre", type: "CHC", distanceKm: 14.2, services: ["PRIMARY_CARE", "CHILD_HEALTH", "MATERNITY", "EMERGENCY"], available: true, hours: "24x7 emergency", address: "Vadakku town (synthetic)", phone: "00000 00003", latitude: 11.12, longitude: 78.11 },
  { id: "dh-demo", name: "District Government Hospital", type: "DISTRICT_HOSPITAL", distanceKm: 27.5, services: ["PRIMARY_CARE", "CHILD_HEALTH", "MATERNITY", "EMERGENCY"], available: true, hours: "24x7", address: "Demo district HQ (synthetic)", phone: "00000 00004", latitude: 11.24, longitude: 78.2 }
];
const queueKey = "ruralcare-referral-queue";
async function request(path: string, init?: RequestInit) { const response = await fetch(path, { headers: { "Content-Type": "application/json" }, ...init }); if (!response.ok) throw new Error("Network unavailable"); return response.json(); }
function queueReferral(data: unknown) { const queue = JSON.parse(localStorage.getItem(queueKey) || "[]"); queue.push(data); localStorage.setItem(queueKey, JSON.stringify(queue)); }
function IconButton({ Icon, children, className = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { Icon?: LucideIcon }) { return <button className={className} {...props}>{Icon && <Icon size={18} strokeWidth={2.3}/>}<span>{children}</span></button>; }

function App() {
  const [language, setLanguage] = useState<"en" | "ta">("en"); const [view, setView] = useState<View>("intake"); const [message, setMessage] = useState(""); const [assessment, setAssessment] = useState<Assessment | null>(null); const [facilities, setFacilities] = useState<Facility[]>([]); const [selected, setSelected] = useState<Facility | null>(null); const [patientLabel, setPatientLabel] = useState("Demo patient"); const [notice, setNotice] = useState(""); const [online, setOnline] = useState(navigator.onLine); const [dashboard, setDashboard] = useState<{ referrals: Referral[]; totals: { total: number; urgent: number; pending: number }; demand: { service: string; count: number }[] } | null>(null);
  const t = useMemo(() => language === "ta" ? { home: "முகப்பு", assistant: "உதவி முறை", title: "சரியான பராமரிப்பு. சரியான நேரத்தில்.", intro: "நாங்கள் உங்கள் தேவையைப் புரிந்து கொண்டு அருகிலுள்ள சரியான பொது சுகாதார சேவைக்குச் செலுத்துகிறோம்.", prompt: "என்ன உதவி தேவை?", next: "பாதுகாப்பாக தொடரவும்", staff: "பணியாளர் பார்வை" } : { home: "Care Compass", assistant: "ASHA-assisted mode", title: "Right care. Right pathway.", intro: "Tell us what you need. We connect you to an appropriate public health service—clearly and safely.", prompt: "What do you need help with?", next: "Continue safely", staff: "Staff view" }, [language]);
  const step = view === "intake" ? 1 : view === "assessment" ? 2 : view === "facilities" ? 3 : view === "referral" ? 4 : 5;
  useEffect(() => { const on = () => setOnline(true); const off = () => setOnline(false); addEventListener("online", on); addEventListener("offline", off); return () => { removeEventListener("online", on); removeEventListener("offline", off); }; }, []);
  useEffect(() => { if (!online) return; const queued = JSON.parse(localStorage.getItem(queueKey) || "[]"); if (!queued.length) return; Promise.all(queued.map((item: unknown) => request("/api/referrals", { method: "POST", body: JSON.stringify(item) }))).then(() => { localStorage.removeItem(queueKey); setNotice("Offline referral synced. Your continuity record is up to date."); }).catch(() => undefined); }, [online]);
  async function triage() { if (!message.trim()) return setNotice("Please describe the health need first."); const local = assessNeed(message); setAssessment(local); setView("assessment"); try { const result = await request("/api/triage", { method: "POST", body: JSON.stringify({ message }) }); setAssessment(result.assessment); } catch { setNotice("Offline-safe assessment is active. You can continue without internet."); } }
  async function findFacilities() { if (!assessment) return; setFacilities(rankFacilities(localFacilities, assessment.service)); setView("facilities"); try { const result = await request(`/api/facilities?service=${assessment.service}`); setFacilities(result.facilities); } catch { setNotice("Showing cached prototype facility data. Please verify before travel."); } }
  async function createReferral() { if (!selected || !assessment) return; const body = { patientLabel, sourceFacility: "ASHA-assisted intake", destinationFacility: selected.name, service: assessment.service, urgency: assessment.urgency, nextAction: assessment.nextAction }; try { const result = await request("/api/referrals", { method: "POST", body: JSON.stringify(body) }); setNotice(`Referral ${result.referral.id.slice(-6)} created. Follow-up is scheduled for tomorrow.`); } catch { queueReferral(body); setNotice("No signal? Referral has been safely saved on this device and will sync later."); } setView("followup"); }
  async function openDashboard() { setView("dashboard"); try { setDashboard(await request("/api/dashboard")); } catch { setNotice("Connect to the local server to load staff activity."); } }
  function startVoice() { const Speech = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Speech) return setNotice("Voice input is unavailable in this browser. Please type your need."); const recognition = new Speech(); recognition.lang = language === "ta" ? "ta-IN" : "en-IN"; recognition.onresult = (event: any) => setMessage(event.results[0][0].transcript); recognition.start(); }
  function emergency() { setMessage("I need emergency help: chest pain"); setAssessment(assessNeed("I need emergency help: chest pain")); setView("assessment"); }
  return <div className="app-shell"><aside><div className="brand"><div className="brand-mark"><HeartPulse/></div><div><b>RuralCare</b><span>CONNECT</span></div></div><nav><button className={view !== "dashboard" ? "active" : ""} onClick={() => setView("intake")}><Sparkles/> {t.home}</button><button onClick={openDashboard}><UsersRound/> {t.staff}</button></nav><div className="aside-card"><div className="signal"><Wifi size={16}/> Offline-first ready</div><p>Saved care journeys continue even when the signal does not.</p><span>Synthetic SIH prototype</span></div><div className="aside-bottom"><ShieldCheck size={18}/><p><b>Safety bounded</b><br/>Not a diagnosis tool</p></div></aside><main><header className="topbar"><div className="mobile-brand"><HeartPulse/><b>RuralCare</b></div><div className="mode-pill"><UsersRound size={15}/>{t.assistant}</div><div className="top-actions"><button className="language" onClick={() => setLanguage(language === "en" ? "ta" : "en")}><Languages size={17}/>{language === "en" ? "தமிழ்" : "English"}</button><button className={online ? "connection online" : "connection offline"}>{online ? <Wifi size={16}/> : <CloudOff size={16}/>}{online ? "Connected" : "Offline"}</button></div></header><div className="prototype-banner"><BadgeCheck size={17}/><span>Public-health navigation prototype</span><i>•</i><span>Synthetic demo data</span><i>•</i><span>Always verify availability before travel</span></div>
  {view !== "dashboard" && <div className="journey"><span>YOUR CARE JOURNEY</span>{["Share", "Understand", "Match", "Refer", "Follow up"].map((name, i) => <div className={i + 1 <= step ? "journey-step done" : "journey-step"} key={name}><b>{i + 1}</b><small>{name}</small></div>)}</div>}
  {notice && <div className="toast"><BadgeCheck size={18}/><span>{notice}</span><button onClick={() => setNotice("")}>×</button></div>}
  {view === "intake" && <section className="home-grid"><div className="welcome-panel"><p className="kicker">CARE COMPASS · RURAL TAMIL NADU</p><h1>{t.title}</h1><p className="lead">{t.intro}</p><div className="input-panel"><label>{t.prompt}<span>Local language welcome</span></label><textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder={language === "ta" ? "உதாரணம்: குழந்தைக்கு இரண்டு நாட்களாக காய்ச்சல் உள்ளது" : "Example: My child has fever and cough for two days"}/><div className="input-actions"><IconButton Icon={Mic} className="ghost" onClick={startVoice}>Speak instead</IconButton><IconButton Icon={ArrowRight} onClick={triage}>{t.next}</IconButton></div></div><div className="safety-strip"><ShieldCheck/><p><b>Clear, not clinical.</b> We help you reach public care; we do not diagnose or prescribe.</p></div></div><div className="right-rail"><div className="quick-panel"><div className="panel-head"><div><span className="eyebrow">GUIDED START</span><h2>Common needs</h2></div><Sparkles className="accent"/></div>{scenarios.map(({ label, tamil, message: scenario, Icon }) => <button className="scenario" key={label} onClick={() => setMessage(scenario)}><span className="scenario-icon"><Icon size={20}/></span><span><b>{label}</b><small>{tamil}</small></span><ArrowRight size={17}/></button>)}</div><button className="emergency-button" onClick={emergency}><AlertTriangle/><span><b>Emergency? Act now</b><small>Immediate human-care guidance</small></span><ArrowRight/></button><div className="signal-card"><MapPin/><div><b>District demo readiness</b><span>4 public facilities · 7 care services</span></div><BadgeCheck/></div></div></section>}
  {view === "assessment" && assessment && <section className="flow-card assessment-layout"><button className="back" onClick={() => setView("intake")}><ChevronLeft/> Back to request</button><div className="flow-title"><p className="kicker">WE LISTENED. PLEASE CONFIRM.</p><h1>{assessment.urgency === "EMERGENCY" ? "Act immediately" : "Your care pathway"}</h1><p>{assessment.explanation}</p></div><div className={`urgency-card ${assessment.urgency.toLowerCase()}`}><div>{assessment.urgency === "EMERGENCY" ? <AlertTriangle/> : <ShieldCheck/>}</div><section><span>SAFETY GUIDANCE</span><h2>{assessment.urgency}</h2><p>{assessment.nextAction}</p></section></div><div className="understood"><div><span>Suggested public service</span><b>{assessment.service.replaceAll("_", " ")}</b></div><div><span>Language</span><b>{assessment.language === "ta" ? "Tamil" : assessment.language}</b></div><div><span>Need signals</span><b>{assessment.symptoms.join(", ")}</b></div></div>{assessment.urgency === "EMERGENCY" ? <div className="emergency-actions"><IconButton Icon={PhoneCall} onClick={() => setNotice("Demo emergency SMS alert prepared.")}>Send demo emergency alert</IconButton><p>This prototype deliberately does not delay emergency care with chat or matching.</p></div> : <div className="flow-actions"><IconButton Icon={ChevronLeft} className="ghost" onClick={() => setView("intake")}>Edit request</IconButton><IconButton Icon={Navigation} onClick={findFacilities}>Find suitable public care</IconButton></div>}</section>}
  {view === "facilities" && assessment && <section className="facilities-page"><div className="section-heading"><div><p className="kicker">CARE MATCHING · NOT JUST NEAREST</p><h1>Public services ready for your need</h1><p>We prioritize required service, demo availability, and travel distance.</p></div><div className="matching-chip"><BadgeCheck/> Safety-checked pathway</div></div><div className="facility-list">{facilities.map((facility, index) => <article className="facility-card" key={facility.id}><div className="rank">0{index + 1}</div><div className="facility-main"><div className="facility-top"><span className="level-tag">{facility.type.replaceAll("_", " ")}</span><span className="live-dot">● Available in demo</span></div><h2>{facility.name}</h2><p><MapPin size={16}/>{facility.address} · <b>{facility.distanceKm} km away</b></p><div className="service-tags">{facility.services.slice(0, 3).map((service) => <span key={service}>{service.replaceAll("_", " ")}</span>)}</div></div><div className="facility-side"><p><b>{facility.hours}</b><small>Demo service hours</small></p><IconButton Icon={ArrowRight} onClick={() => { setSelected(facility); setView("referral"); }}>Choose pathway</IconButton></div></article>)}</div><button className="back text-button" onClick={() => setView("assessment")}><ChevronLeft/> Review assessment</button></section>}
  {view === "referral" && selected && assessment && <section className="referral-page"><div className="referral-card"><div className="referral-header"><div className="brand-mark"><ClipboardPlus/></div><div><span>RURALCARE CONNECT</span><h1>Continuity pass</h1></div><BadgeCheck/></div><p className="muted">A simple hand-off so the next public facility understands the care need without making the patient start over.</p><label>Patient label <small>Demo only; no real personal data</small><input value={patientLabel} onChange={(e) => setPatientLabel(e.target.value)} maxLength={40}/></label><div className="pass-row"><span>CARE NEED</span><b>{assessment.service.replaceAll("_", " ")}</b></div><div className="pass-row"><span>ROUTED TO</span><b>{selected.name}</b></div><div className="pass-row"><span>NEXT ACTION</span><b>{assessment.nextAction}</b></div><div className="referral-foot"><ShieldCheck/><span>Structured, shareable context · Prototype only</span></div></div><div className="referral-copy"><p className="kicker">REFERRAL CONTINUITY</p><h1>One care story, carried forward.</h1><p>The novelty is not merely AI triage. It is a safety-bounded hand-off from citizen need to a suitable public service, with a follow-up loop.</p><div className="mini-points"><span><BadgeCheck/> Service-aware referral</span><span><CloudOff/> Stores safely offline</span><span><UsersRound/> Staff coordination view</span></div><div className="flow-actions"><IconButton Icon={ChevronLeft} className="ghost" onClick={() => setView("facilities")}>Choose another facility</IconButton><IconButton Icon={ClipboardPlus} onClick={createReferral}>Create continuity pass</IconButton></div></div></section>}
  {view === "followup" && <section className="followup-page"><div className="success-mark"><BadgeCheck/></div><p className="kicker">CARE JOURNEY SAVED</p><h1>Your next step is clear.</h1><p>We have created—or safely queued—your prototype referral and follow-up plan.</p><div className="timeline"><div><span>NOW</span><section><b>Referral continuity pass</b><p>Care context is ready for the receiving public facility.</p></section></div><div><span>TOMORROW</span><section><b>Follow-up reminder</b><p>Confirm whether the facility was reached and next care started.</p></section></div><div><span>STAFF</span><section><b>Demand signal updates</b><p>Non-identifying referral demand improves coordination visibility.</p></section></div></div><div className="flow-actions"><IconButton Icon={UsersRound} className="ghost" onClick={openDashboard}>View staff coordination</IconButton><IconButton Icon={Sparkles} onClick={() => { setView("intake"); setMessage(""); setAssessment(null); setSelected(null); }}>Start another journey</IconButton></div></section>}
  {view === "dashboard" && <section className="dashboard"><div className="section-heading"><div><p className="kicker">ASHA / PHC COORDINATION VIEW</p><h1>Care continuity, at a glance.</h1><p>Only synthetic, non-identifying prototype activity is shown here.</p></div><button className="back" onClick={() => setView("intake")}><ChevronLeft/> Citizen journey</button></div>{dashboard ? <><div className="metric-grid"><article><ClipboardPlus/><b>{dashboard.totals.total}</b><span>Care journeys referred</span></article><article><AlertTriangle/><b>{dashboard.totals.urgent}</b><span>Priority pathways</span></article><article><CalendarDays/><b>{dashboard.totals.pending}</b><span>Follow-ups due</span></article></div><div className="dashboard-grid"><article className="demand-panel"><p className="eyebrow">SERVICE DEMAND SIGNALS</p><h2>Where people need help</h2>{dashboard.demand.map((d, i) => <div className="bar" key={d.service}><span>{d.service}</span><div><i style={{ width: `${[86, 58, 35][i]}%` }}/></div><b>{d.count}</b></div>)}<p className="small">Signals are aggregated and synthetic; they are not clinical prevalence data.</p></article><article className="referral-panel"><p className="eyebrow">RECENT CONTINUITY PASSES</p><h2>Incoming coordination</h2>{dashboard.referrals.length ? dashboard.referrals.map((r) => <div className="referral-row" key={r.id}><span className="avatar">{r.patientLabel.slice(0, 1).toUpperCase()}</span><div><b>{r.patientLabel}</b><small>{r.destinationFacility}</small></div><span className="status">{r.status}</span></div>) : <div className="empty"><ClipboardPlus/><p>No referrals yet. Complete a citizen journey to see one here.</p></div>}</article></div></> : <div className="loading-card">Loading local coordination data…</div>}</section>}
  </main></div>;
}
declare global { interface Window { SpeechRecognition?: any; webkitSpeechRecognition?: any; } }
createRoot(document.getElementById("root")!).render(<App/>);
