export type SyncState="LOCAL_ONLY"|"PENDING_SYNC"|"SYNCING"|"SYNCED"|"SYNC_FAILED";
const DB="ruralcare-offline",STORE="workflow",QUEUE="actions";
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE);if(!db.objectStoreNames.contains(QUEUE))db.createObjectStore(QUEUE,{keyPath:"id"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
export async function saveWorkflow(ownerUserId:string,value:unknown){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value,`current:${ownerUserId}`);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}
export async function loadWorkflow<T>(ownerUserId:string){const db=await openDb();const value=await new Promise<T|undefined>((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).get(`current:${ownerUserId}`);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});db.close();return value;}
export async function clearWorkflow(ownerUserId:string){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(`current:${ownerUserId}`);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}
export async function queueAction(ownerUserId:string,action:{id:string;path:string;method:string;body:unknown}){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(QUEUE,"readwrite");tx.objectStore(QUEUE).put({...action,id:`${ownerUserId}:${action.id}`,actionId:action.id,ownerUserId});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}
export async function pendingActions(ownerUserId:string){const db=await openDb();const items=await new Promise<Array<{id:string;actionId:string;ownerUserId:string;path:string;method:string;body:unknown}>>((resolve,reject)=>{const request=db.transaction(QUEUE).objectStore(QUEUE).getAll();request.onsuccess=()=>resolve(request.result.filter((item:{ownerUserId?:string})=>item.ownerUserId===ownerUserId));request.onerror=()=>reject(request.error);});db.close();return items;}
export async function removeAction(id:string){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(QUEUE,"readwrite");tx.objectStore(QUEUE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}
