export type Urgency="EMERGENCY"|"URGENT"|"ROUTINE"|"INSUFFICIENT_INFORMATION";
export type Service="PRIMARY_CARE"|"MATERNITY"|"CHILD_HEALTH"|"EMERGENCY"|"TELECONSULT";
export type CapacityStatus="AVAILABLE"|"LIMITED"|"UNAVAILABLE";
export type ServiceCapacity={status:CapacityStatus;estimatedWaitMinutes:number;availableBeds:number;note:string};
export type CapabilitySource="SOURCED_FROM_DIRECTORY"|"INFERRED_FROM_FACILITY_TYPE";
export type TriggeredRule={triggeredRuleId:string;finding:string;guidelineReference:string;explanation:string};
export type ClinicalExtraction={ageGroup:"CHILD"|"ADULT"|"UNKNOWN";symptoms:string[];duration:string;childFever:boolean;canDrink:boolean|null;repeatedVomiting:boolean|null;convulsions:boolean|null;consciousnessChange:boolean|null;breathingDifficulty:boolean|null;stiffNeck:boolean|null;severeBleeding:boolean|null;pregnancy:boolean|null};
export type Assessment={urgency:Urgency;service:Service;symptoms:string[];duration:string;explanation:string;nextAction:string;language:"ta"|"en"|"mixed";redFlags:string[];extraction:ClinicalExtraction;triggeredRules:TriggeredRule[];missingInformation:string[]};
export type Facility={id:string;name:string;type:"AAM"|"PHC"|"CHC"|"DISTRICT_HOSPITAL"|"DISPENSARY";distanceKm:number;services:Service[];available:boolean;hours:string;address:string;phone:string;latitude:number;longitude:number;capacity?:Partial<Record<Service,ServiceCapacity>>;lastUpdated?:string;operationalSource?:"SIMULATED_FOR_PROTOTYPE"|"FACILITY_STAFF_REPORTED";capabilitySource?:CapabilitySource;serviceSources?:Partial<Record<Service,CapabilitySource>>};

const refs={child:"WHO IMCI Chart Booklet (2014): child danger signs include inability to drink/breastfeed, vomiting everything, convulsions, lethargy or unconsciousness.",fever:"WHO IMCI Chart Booklet (2014): stiff neck is a severe finding in child fever assessment.",adult:"WHO/ICRC Basic Emergency Care (2018): breathing difficulty, altered consciousness and severe chest symptoms require immediate assessment.",pregnancy:"WHO antenatal-care guidance: pregnancy danger concerns require prompt in-person assessment."};
const terms={child:["child","baby","infant","toddler","kuzhandhai","kuzhandai","kulandhai","குழந்தை","சிசு"],fever:["fever","temperature","kaichal","kaaichal","காய்ச்சல்"],drinkNo:["cannot drink","can't drink","not drinking","unable to drink","kudikka mudiyala","kudika mudiyala","குடிக்க முடிய","குடிக்கவில்லை"],drinkYes:["drinking well","can drink","feeding well","drinking normally","kudikkuthu","kudikiran","குடிக்கிறார்","குடிக்க முடிகிறது"],vomit:["vomits everything","vomiting everything","repeated vomiting","keeps vomiting","vanthi ellame","thodarndhu vanthi","தொடர்ந்து வாந்தி","எல்லாவற்றையும் வாந்தி"],seizure:["seizure","convulsion","fits","valippu","வலிப்பு"],consciousness:["unconscious","not waking","difficult to wake","confused","lethargic","mayakkam","ezhuppa mudiyala","மயக்கம்","எழுப்ப முடியவில்லை","சுயநினைவு இல்லை"],breathing:["not breathing","difficulty breathing","shortness of breath","breathless","moochu kashtam","மூச்சு கஷ்டம்","மூச்சு திணறல்"],stiff:["stiff neck","neck stiffness","kazhuthu viraippu","கழுத்து விறைப்பு"],bleeding:["severe bleeding","heavy bleeding","romba bleeding","kadumaiyana rathappokku","கடுமையான இரத்தப்போக்கு"],pregnancy:["pregnant","pregnancy","labour","labor","karpam","garbham","கர்ப்ப","பிரசவ"],chest:["chest pain","chest pressure","nenju vali","மார்பு வலி","மார்பு அழுத்தம்"]};
const has=(text:string,values:string[])=>values.some(value=>text.includes(value));
const mention=(text:string,positive:string[],negative:string[])=>has(text,negative)?false:has(text,positive)?true:null;
const tanglishLanguage=/\b(ku|irukku|iruku|illa|venum|kuzhandhai|karpam|kaichal|moochu|vanthi|valippu|thalaivali|vayitru|nenju|kammi|aachu|solrar|pannunga|ezhuppa|mudiyala)\b/i;
const language=(text:string):Assessment["language"]=>/[\u0B80-\u0BFF]/.test(text)?(/[a-z]/i.test(text)?"mixed":"ta"):tanglishLanguage.test(text)?"mixed":"en";
const makeRule=(triggeredRuleId:string,finding:string,guidelineReference:string,explanation:string):TriggeredRule=>({triggeredRuleId,finding,guidelineReference,explanation});

export function extractClinicalInformation(message:string):ClinicalExtraction{
  const text=message.toLowerCase(),ageGroup=has(text,terms.child)?"CHILD":/adult|elderly|woman|man|years?[- ]old| வயது/.test(text)?"ADULT":"UNKNOWN";
  const repeatedVomiting=mention(text,terms.vomit,["no vomiting","not vomiting","no repeated vomiting","vanthi illa","வாந்தி இல்லை"]),breathingDifficulty=mention(text,terms.breathing,["no breathing difficulty","no difficulty breathing","breathing normally","moochu kashtam illa","மூச்சு பிரச்சனை இல்லை","மூச்சு திணறல் இல்லை"]),severeBleeding=mention(text,terms.bleeding,["no bleeding","no severe bleeding","no heavy bleeding","bleeding illa","இரத்தப்போக்கு இல்லை"]);
  const symptoms=[has(text,terms.fever)&&"fever",has(text,terms.chest)&&"chest discomfort",breathingDifficulty===true&&"breathing difficulty",repeatedVomiting===true&&"vomiting",severeBleeding===true&&"bleeding",has(text,terms.pregnancy)&&"pregnancy-related concern"].filter(Boolean) as string[];
  return {ageGroup,symptoms,duration:/\d+\s*(day|days|week|weeks|hour|hours|naal|mani|நாள்|மணி)/.test(text)||/since (this )?morning|காலை முதல்/.test(text)?"Mentioned by user":"Not specified",childFever:ageGroup==="CHILD"&&has(text,terms.fever),canDrink:mention(text,terms.drinkYes,terms.drinkNo),repeatedVomiting,convulsions:mention(text,terms.seizure,["no seizure","no convulsion","no fits","valippu illa","வலிப்பு இல்லை"]),consciousnessChange:mention(text,terms.consciousness,["awake","alert","active and playing","not confused","no confusion","mayakkam illa","active ah irukku","மயக்கம் இல்லை","விழிப்புடன்","சுறுசுறுப்பாக உள்ளது"]),breathingDifficulty,stiffNeck:mention(text,terms.stiff,["no stiff neck","no neck stiffness","kazhuthu viraippu illa","கழுத்து விறைப்பு இல்லை"]),severeBleeding,pregnancy:has(text,terms.pregnancy)?true:null};
}
function result(base:Omit<Assessment,"language">,message:string):Assessment{return {...base,language:language(message)};}
export function assessNeed(message:string):Assessment{
  const e=extractClinicalInformation(message),rules:TriggeredRule[]=[];
  if(e.severeBleeding)rules.push(makeRule("EMR_SEVERE_BLEEDING","Severe bleeding was described.",refs.adult,"Heavy bleeding can require immediate in-person help; this app cannot identify its cause."));
  if(e.convulsions)rules.push(makeRule("EMR_CONVULSION","A convulsion or seizure was described.",refs.child,"A seizure is a danger sign requiring immediate in-person assessment."));
  if(e.consciousnessChange)rules.push(makeRule("EMR_ALTERED_CONSCIOUSNESS","Loss of consciousness, confusion, or difficulty waking was described.",refs.child,"A change in alertness is a danger sign requiring immediate in-person assessment."));
  if(e.breathingDifficulty)rules.push(makeRule("EMR_BREATHING_DIFFICULTY","Difficulty breathing was described.",refs.adult,"Breathing difficulty can be high risk and requires immediate in-person assessment."));
  if(e.childFever&&e.stiffNeck)rules.push(makeRule("EMR_CHILD_FEVER_STIFF_NECK","A child with fever and stiff neck was described.",refs.fever,"This combination is a child danger sign requiring immediate help."));
  if(e.ageGroup==="CHILD"&&e.canDrink===false)rules.push(makeRule("EMR_CHILD_UNABLE_TO_DRINK","The child was reported unable to drink or breastfeed.",refs.child,"Inability to drink is a child danger sign requiring immediate assessment."));
  if(e.ageGroup==="CHILD"&&e.repeatedVomiting)rules.push(makeRule("EMR_CHILD_VOMITS_EVERYTHING","The child was reported to be vomiting repeatedly or everything.",refs.child,"Vomiting everything is a child danger sign requiring immediate assessment."));
  const service:Service=e.pregnancy?"MATERNITY":e.ageGroup==="CHILD"?"CHILD_HEALTH":"PRIMARY_CARE";
  if(rules.length)return result({urgency:"EMERGENCY",service:"EMERGENCY",symptoms:e.symptoms.length?e.symptoms:["Reported danger sign"],duration:e.duration,redFlags:rules.map(item=>item.finding),extraction:e,triggeredRules:rules,missingInformation:[],explanation:"Immediate high-risk warning signs were reported. This is not a diagnosis.",nextAction:"Seek immediate in-person emergency help. Do not wait for an app response."},message);
  if(e.childFever&&(e.canDrink===null||e.repeatedVomiting===null||e.convulsions===null||e.consciousnessChange===null||e.breathingDifficulty===null||e.stiffNeck===null)){
    const missingInformation=[e.canDrink===null&&"Can the child drink or breastfeed normally?",e.repeatedVomiting===null&&"Is the child vomiting everything or repeatedly?",(e.convulsions===null||e.consciousnessChange===null)&&"Has the child had a seizure or become difficult to wake?",(e.breathingDifficulty===null||e.stiffNeck===null)&&"Does the child have difficulty breathing or a stiff neck?"].filter(Boolean) as string[];
    return result({urgency:"INSUFFICIENT_INFORMATION",service,symptoms:e.symptoms,duration:e.duration,redFlags:[],extraction:e,triggeredRules:[],missingInformation,explanation:"A mild child fever alone is not automatically urgent. A few safety answers are needed before routing.",nextAction:"Answer the safety questions, or seek a health worker’s help if you are worried."},message);
  }
  const text=message.toLowerCase();
  if(has(text,terms.chest)&&!/mild|slight|லேசான/.test(text))return result({urgency:"INSUFFICIENT_INFORMATION",service,symptoms:e.symptoms,duration:e.duration,redFlags:[],extraction:e,triggeredRules:[],missingInformation:["Is there difficulty breathing, fainting, confusion, or severe sweating?","Did the chest discomfort start suddenly or become severe?"],explanation:"More safety information is needed before classifying chest discomfort.",nextAction:"Answer the questions; seek immediate human help if symptoms are severe or worsening."},message);
  if(e.pregnancy&&/bleeding|rathappokku|இரத்தப்போக்கு|severe (abdominal |stomach )?pain|kadumaiyana vayitru vali|கடுமையான வயிற்று வலி|reduced (baby |fetal )?movement|baby'?s? movement.*reduc|baby movement kammi|குழந்தை அசைவு குறை|நடமாட்டம் குறை|severe headache|kadumaiyana thalaivali|கடுமையான தலைவலி/.test(text)){const rule=makeRule("URG_PREGNANCY_DANGER_CONCERN","A pregnancy-related warning concern was described.",refs.pregnancy,"Prompt same-day assessment is recommended; this app cannot diagnose the cause.");return result({urgency:"URGENT",service,symptoms:e.symptoms,duration:e.duration,redFlags:[rule.finding],extraction:e,triggeredRules:[rule],missingInformation:[],explanation:rule.explanation,nextAction:"Arrange prompt same-day assessment at a suitable public facility."},message);}
  return result({urgency:"ROUTINE",service,symptoms:e.symptoms.length?e.symptoms:["General health concern"],duration:e.duration,redFlags:[],extraction:e,triggeredRules:[],missingInformation:[],explanation:"No urgent warning signs were identified from the information provided. This is navigation support, not medical diagnosis.",nextAction:"Use an appropriate public primary-care service, or seek human help sooner if symptoms worsen."},message);
}

export function calculateDistanceKm(from:{latitude:number;longitude:number},to:{latitude:number;longitude:number}){const radians=(v:number)=>v*Math.PI/180,dLat=radians(to.latitude-from.latitude),dLong=radians(to.longitude-from.longitude),a=Math.sin(dLat/2)**2+Math.cos(radians(from.latitude))*Math.cos(radians(to.latitude))*Math.sin(dLong/2)**2;return Math.round(6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))*10)/10;}
export function travelMinutes(facility:Facility){return Math.max(6,Math.round(facility.distanceKm*4.2));}
export function serviceCapacity(facility:Facility,service:Service):ServiceCapacity{return facility.capacity?.[service]||{status:facility.available?"AVAILABLE":"UNAVAILABLE",estimatedWaitMinutes:facility.available?30:0,availableBeds:0,note:facility.available?"Synthetic demo status":"Unavailable in synthetic demo shift"};}
const levelScore:Record<Facility["type"],number>={AAM:1,DISPENSARY:1,PHC:2,CHC:3,DISTRICT_HOSPITAL:4},capacityScore:Record<CapacityStatus,number>={AVAILABLE:3,LIMITED:2,UNAVAILABLE:0};
export function rankFacilities(facilities:Facility[],service:Service,urgency:Urgency="ROUTINE"){return facilities.filter(f=>f.services.includes(service)&&serviceCapacity(f,service).status!=="UNAVAILABLE").sort((a,b)=>{const ac=serviceCapacity(a,service),bc=serviceCapacity(b,service),weight=urgency==="EMERGENCY"?3:2;return capacityScore[bc.status]*12+levelScore[b.type]*weight-travelMinutes(b)/10-bc.estimatedWaitMinutes/20-(capacityScore[ac.status]*12+levelScore[a.type]*weight-travelMinutes(a)/10-ac.estimatedWaitMinutes/20);});}
export {classifyService,routeFacilities,ROUTING_WEIGHTS,type CareLevel,type RouteCandidate,type RouteDecision,type ServicePlan} from "./routing.ts";
export {applyAdaptiveAnswer,detectClinicalContradictions,detectInputLanguage,extractStructuredNeed,nextSafetyQuestion,safetyQuestionRegistry,structuredToMessage,withMissing,type AdaptiveAnswer,type InputLanguage,type ResponseLanguage,type SafetyQuestion,type StructuredIntake,type StructuredSymptom} from "./intake.ts";
export {buildEvaluationCorpus,evaluationCorpus,evaluationSources,type EvaluationCase,type EvaluationLanguage,type ExpectedRoute} from "./evaluation-corpus.ts";
