import assert from "node:assert/strict";
import test from "node:test";
import { assessNeed, routeFacilities, type Facility } from "./index.ts";

const facility = (id:string, type:Facility["type"], distanceKm:number, services:Facility["services"], availability:"AVAILABLE"|"UNAVAILABLE"="AVAILABLE", capabilitySource:Facility["capabilitySource"]="SOURCED_FROM_DIRECTORY"):Facility => ({ id,name:id,type,distanceKm,services,available:availability!=="UNAVAILABLE",hours:"Synthetic",address:"Demo",phone:"",latitude:12+distanceKm/100,longitude:80,capacity:Object.fromEntries(services.map(service=>[service,{status:availability,estimatedWaitMinutes:15,availableBeds:1,note:"Synthetic"}])),capabilitySource,serviceSources:Object.fromEntries(services.map(service=>[service,capabilitySource])) });
const stableChild = assessNeed("8-year-old child has mild fever since morning, drinking well, no vomiting, no seizure, no breathing difficulty, no stiff neck, awake");
test("service suitability outranks an inappropriate nearer facility",()=>{const decision=routeFacilities([facility("near-primary","PHC",2,["PRIMARY_CARE"]),facility("child-chc","CHC",7,["CHILD_HEALTH"])],stableChild);assert.equal(decision.selectedFacilityId,"child-chc");});
test("unavailable original match triggers deterministic rerouting",()=>{const decision=routeFacilities([facility("nearest","PHC",2,["CHILD_HEALTH"],"UNAVAILABLE"),facility("next","CHC",5,["CHILD_HEALTH"])],stableChild);assert.equal(decision.rerouted,true);assert.equal(decision.originalFacilityId,"nearest");assert.equal(decision.selectedFacilityId,"next");});
test("capability provenance is preserved in comparison candidates",()=>{const decision=routeFacilities([facility("inferred","PHC",2,["CHILD_HEALTH"],"AVAILABLE","INFERRED_FROM_FACILITY_TYPE"),facility("sourced","CHC",4,["CHILD_HEALTH"])],stableChild);assert.equal(decision.candidates[0].serviceSources?.CHILD_HEALTH,"SOURCED_FROM_DIRECTORY");});
test("emergency routing rejects closest basic primary facility",()=>{const emergency=assessNeed("severe chest pain and difficulty breathing");const decision=routeFacilities([facility("basic","PHC",1,["PRIMARY_CARE"]),facility("emergency-hospital","DISTRICT_HOSPITAL",8,["EMERGENCY"])],emergency);assert.equal(decision.selectedFacilityId,"emergency-hospital");});
test("invalid coordinates have no fabricated distance candidate",()=>{const invalid={...facility("invalid","PHC",1,["CHILD_HEALTH"]),latitude:0,longitude:0};const decision=routeFacilities([invalid],stableChild);assert.equal(decision.selectedFacilityId,null);assert.equal(decision.candidates.length,0);});
