import bcrypt from "bcryptjs";
import { Router } from "express";
import rateLimit from "express-rate-limit";
import { OAuth2Client } from "google-auth-library";
import { z } from "zod";
import { clearSession, issueSession, requireAuth, type AuthRequest, type SessionUser } from "./auth.ts";
import { prisma } from "./prisma.ts";

type VerifiedGoogleProfile={sub:string;email:string;emailVerified:boolean;name:string;picture?:string};
export type GoogleCredentialVerifier=(credential:string,audience:string)=>Promise<VerifiedGoogleProfile>;
export const verifyGoogleCredential:GoogleCredentialVerifier=async(credential,audience)=>{const ticket=await new OAuth2Client({clientId:audience}).verifyIdToken({idToken:credential,audience}),payload=ticket.getPayload();if(!payload?.sub||!payload.email||payload.email_verified!==true)throw new Error("Google identity is incomplete or unverified.");return{sub:payload.sub,email:payload.email,emailVerified:true,name:payload.name||payload.email.split("@")[0],picture:payload.picture};};
const normalizeEmail=(email:string)=>email.trim().toLowerCase();
const safeUser=(row:{id:string;name:string;email:string|null;phone:string|null;role:string;facilityId:string|null;preferredLanguage:string;village:string|null}):SessionUser=>({id:row.id,name:row.name,email:row.email,phone:row.phone,role:row.role as SessionUser["role"],facilityId:row.facilityId,preferredLanguage:row.preferredLanguage==="ta"?"ta":"en",village:row.village});

export function createAuthRouter(googleVerifier:GoogleCredentialVerifier=verifyGoogleCredential){
 const router=Router(),limit=rateLimit({windowMs:10*60*1000,limit:20,standardHeaders:true,legacyHeaders:false,message:{error:"Too many authentication attempts. Please wait and try again."}});
 router.post("/register",limit,async(req,res)=>{const parsed=z.object({name:z.string().trim().min(2).max(60),email:z.string().trim().email().max(160),password:z.string().min(8).max(72),confirmPassword:z.string().min(8).max(72),preferredLanguage:z.enum(["en","ta"]).optional(),village:z.string().trim().min(2).max(80).optional()}).strict().refine(value=>value.password===value.confirmPassword,{message:"Passwords do not match."}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message||"Invalid registration."});const email=normalizeEmail(parsed.data.email);if(await prisma.user.findUnique({where:{email},select:{id:true}}))return res.status(409).json({error:"An account already exists for that email."});const passwordHash=await bcrypt.hash(parsed.data.password,12),timestamp=new Date().toISOString(),row=await prisma.user.create({data:{id:crypto.randomUUID(),name:parsed.data.name,email,passwordHash,role:"CITIZEN",facilityId:null,preferredLanguage:parsed.data.preferredLanguage||"en",village:parsed.data.village||null,createdAt:timestamp,updatedAt:timestamp},select:{id:true,name:true,email:true,phone:true,role:true,facilityId:true,preferredLanguage:true,village:true}}),user=safeUser(row);issueSession(res,user);res.status(201).json({user});});
 router.post("/login",limit,async(req,res)=>{const parsed=z.object({email:z.string().trim().email().max(160).optional(),identifier:z.string().trim().email().max(160).optional(),password:z.string().min(1).max(72)}).strict().refine(value=>value.email||value.identifier).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Enter a valid email and password."});const row=await prisma.user.findUnique({where:{email:normalizeEmail(parsed.data.email||parsed.data.identifier!)}});if(!row?.passwordHash||!await bcrypt.compare(parsed.data.password,row.passwordHash))return res.status(401).json({error:"Invalid email or password."});const user=safeUser(row);issueSession(res,user);res.json({user});});
 router.post("/google",limit,async(req,res)=>{const parsed=z.object({credential:z.string().min(100).max(10000)}).strict().safeParse(req.body),audience=process.env.GOOGLE_CLIENT_ID?.trim();if(!audience)return res.status(503).json({error:"Google sign-in is not configured."});if(!parsed.success)return res.status(400).json({error:"A valid Google credential is required."});try{const verified=await googleVerifier(parsed.data.credential,audience);if(!verified.sub||!verified.email||verified.emailVerified!==true)throw new Error("unverified");const email=normalizeEmail(verified.email),timestamp=new Date().toISOString();let row=await prisma.user.findUnique({where:{googleSub:verified.sub}});if(!row){const sameEmail=await prisma.user.findUnique({where:{email}});row=sameEmail?await prisma.user.update({where:{id:sameEmail.id},data:{googleSub:verified.sub,avatarUrl:sameEmail.avatarUrl||verified.picture||null,updatedAt:timestamp}}):await prisma.user.create({data:{id:crypto.randomUUID(),name:verified.name,email,googleSub:verified.sub,avatarUrl:verified.picture||null,passwordHash:null,role:"CITIZEN",facilityId:null,preferredLanguage:"en",createdAt:timestamp,updatedAt:timestamp}});}const user=safeUser(row);issueSession(res,user);res.json({user});}catch{return res.status(401).json({error:"Google sign-in could not be verified."});}});
 router.get("/me",requireAuth,(req:AuthRequest,res)=>res.json({user:req.user}));
 router.post("/logout",(_req,res)=>{clearSession(res);res.json({ok:true});});
 return router;
}
