import assert from "node:assert/strict";
import test from "node:test";
import bcrypt from "bcryptjs";
import { app } from "./index.ts";
import { db, initializeDatabase } from "./db.ts";

type CallResult={status:number;data:any;cookie:string};
test("Milestone 4 authentication, ownership, and facility authorization",async t=>{initializeDatabase();const server=app.listen(0),address=server.address();assert.ok(address&&typeof address==="object");const base=`http://127.0.0.1:${address.port}`;const call=async(path:string,init:RequestInit={},cookie=""):Promise<CallResult>=>{const response=await fetch(`${base}${path}`,{...init,headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{}),...(init.headers||{})}}),setCookie=response.headers.get("set-cookie")||"";return{status:response.status,data:await response.json().catch(()=>({})),cookie:setCookie.split(";")[0]||cookie};};let citizenCookie="",otherCookie="",ashaCookie="",staffCookie="",otherStaffCookie="",referralId="",ashaReferralId="";try{
  await t.test("Citizen registration hashes the password and restores auth/me",async()=>{const email=`citizen-${Date.now()}@test.local`,result=await call("/api/auth/register",{method:"POST",body:JSON.stringify({name:"Test Citizen",email,password:"StrongPass@123",confirmPassword:"StrongPass@123"})});assert.equal(result.status,201);citizenCookie=result.cookie;const stored=db.prepare("SELECT passwordHash,role FROM User WHERE email=?").get(email) as {passwordHash:string;role:string};assert.notEqual(stored.passwordHash,"StrongPass@123");assert.ok(await bcrypt.compare("StrongPass@123",stored.passwordHash));assert.equal(stored.role,"CITIZEN");const me=await call("/api/auth/me",{},citizenCookie);assert.equal(me.status,200);assert.equal(me.data.user.role,"CITIZEN");});
  await t.test("Invalid password fails and unauthenticated protected API is rejected",async()=>{const bad=await call("/api/auth/login",{method:"POST",body:JSON.stringify({identifier:"citizen.demo@ruralcare.local",password:"wrong-password"})});assert.equal(bad.status,401);assert.equal((await call("/api/referrals")).status,401);});
  await t.test("Citizen creates and sees only their own referral",async()=>{const created=await call("/api/referrals",{method:"POST",body:JSON.stringify({clientId:crypto.randomUUID(),patientLabel:"Ownership test",sourceFacility:"Citizen pathway",destinationFacility:"Public Health Centre",selectedFacilityId:"public-health-centre-west-mambalam",service:"PRIMARY_CARE",urgency:"ROUTINE",nextAction:"Prototype care visit",sourceMode:"CITIZEN"})},citizenCookie);assert.equal(created.status,201);referralId=created.data.referral.id;assert.equal((await call(`/api/referrals/${referralId}`,{},citizenCookie)).status,200);const email=`other-${Date.now()}@test.local`,other=await call("/api/auth/register",{method:"POST",body:JSON.stringify({name:"Other Citizen",email,password:"StrongPass@123",confirmPassword:"StrongPass@123"})});otherCookie=other.cookie;assert.equal((await call(`/api/referrals/${referralId}`,{},otherCookie)).status,403);assert.equal((await call("/api/coordination",{},citizenCookie)).status,403);});
  await t.test("ASHA sees assisted referrals they created, not unrelated citizen referrals",async()=>{const login=await call("/api/auth/login",{method:"POST",body:JSON.stringify({identifier:"asha.demo@ruralcare.local",password:"RuralCare@2026"})});ashaCookie=login.cookie;const created=await call("/api/referrals",{method:"POST",body:JSON.stringify({clientId:crypto.randomUUID(),patientLabel:"Assisted demo",sourceFacility:"ASHA-assisted pathway",destinationFacility:"Public Health Centre",selectedFacilityId:"public-health-centre-west-mambalam",service:"CHILD_HEALTH",urgency:"ROUTINE",nextAction:"Prototype child-health visit",sourceMode:"ASHA_ASSISTED"})},ashaCookie);assert.equal(created.status,201);ashaReferralId=created.data.referral.id;assert.equal((await call(`/api/referrals/${ashaReferralId}`,{},ashaCookie)).status,200);assert.equal((await call(`/api/referrals/${referralId}`,{},ashaCookie)).status,403);});
  await t.test("Staff is facility-scoped for referrals and capacity",async()=>{const login=await call("/api/auth/login",{method:"POST",body:JSON.stringify({identifier:"staff.demo@ruralcare.local",password:"RuralCare@2026"})});staffCookie=login.cookie;assert.equal(login.data.user.facilityId,"public-health-centre-west-mambalam");assert.equal((await call(`/api/referrals/${referralId}`,{},staffCookie)).status,200);assert.equal((await call("/api/capacity/public-health-centre-west-mambalam/PRIMARY_CARE",{method:"PUT",body:JSON.stringify({availability:"LIMITED"})},staffCookie)).status,200);assert.equal((await call("/api/capacity/rajiv-gandhi-government-general-hospital/PRIMARY_CARE",{method:"PUT",body:JSON.stringify({availability:"LIMITED"})},staffCookie)).status,403);});
  await t.test("Doctor receives assigned referrals but cannot manage capacity",async()=>{const login=await call("/api/auth/login",{method:"POST",body:JSON.stringify({identifier:"doctor.demo@ruralcare.local",password:"RuralCare@2026"})});assert.equal(login.status,200);assert.equal(login.data.user.role,"DOCTOR");assert.equal((await call("/api/coordination",{},login.cookie)).status,200);assert.equal((await call(`/api/referrals/${referralId}`,{},login.cookie)).status,200);assert.equal((await call("/api/capacity",{},login.cookie)).status,403);});
  await t.test("Facility admin can manage only assigned facility capacity",async()=>{const login=await call("/api/auth/login",{method:"POST",body:JSON.stringify({identifier:"admin.demo@ruralcare.local",password:"RuralCare@2026"})});assert.equal(login.status,200);assert.equal(login.data.user.role,"FACILITY_ADMIN");assert.equal((await call("/api/capacity",{},login.cookie)).status,200);assert.equal((await call("/api/capacity/public-health-centre-west-mambalam/PRIMARY_CARE",{method:"PUT",body:JSON.stringify({availability:"AVAILABLE"})},login.cookie)).status,200);assert.equal((await call("/api/capacity/rajiv-gandhi-government-general-hospital/PRIMARY_CARE",{method:"PUT",body:JSON.stringify({availability:"AVAILABLE"})},login.cookie)).status,403);});
  await t.test("Valid status transitions succeed and invalid transitions fail",async()=>{assert.equal((await call(`/api/referrals/${referralId}`,{method:"PATCH",body:JSON.stringify({status:"ACCEPTED"})},staffCookie)).status,200);assert.equal((await call(`/api/referrals/${referralId}`,{method:"PATCH",body:JSON.stringify({status:"COMPLETED"})},staffCookie)).status,409);});
  await t.test("Confirmed reroute moves active staff ownership",async()=>{const hash=await bcrypt.hash("RuralCare@2026",12),timestamp=new Date().toISOString();db.prepare("INSERT OR REPLACE INTO User (id,name,email,phone,passwordHash,role,facilityId,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?)").run("test-staff-gh","Test Hospital Staff","staff.gh@test.local",null,hash,"STAFF","rajiv-gandhi-government-general-hospital",timestamp,timestamp);const login=await call("/api/auth/login",{method:"POST",body:JSON.stringify({identifier:"staff.gh@test.local",password:"RuralCare@2026"})});otherStaffCookie=login.cookie;db.prepare("UPDATE Referral SET recommendedFacility=?,recommendedFacilityId=?,rerouteStatus='REROUTE_RECOMMENDED' WHERE id=?").run("Government General Hospital","rajiv-gandhi-government-general-hospital",referralId);assert.equal((await call(`/api/referrals/${referralId}/reroute/confirm`,{method:"POST"},citizenCookie)).status,200);assert.equal((await call(`/api/referrals/${referralId}`,{},staffCookie)).status,403);assert.equal((await call(`/api/referrals/${referralId}`,{},otherStaffCookie)).status,200);});
  await t.test("Logout invalidates browser session",async()=>{const logout=await call("/api/auth/logout",{method:"POST"},otherCookie);assert.equal(logout.status,200);assert.equal((await call("/api/auth/me",{},logout.cookie)).status,401);});
  assert.ok(ashaReferralId);
}finally{db.exec("DELETE FROM ReferralStatusEvent WHERE referralId IN (SELECT id FROM Referral WHERE patientLabel IN ('Ownership test','Assisted demo')); DELETE FROM FollowUpOutcome WHERE referralId IN (SELECT id FROM Referral WHERE patientLabel IN ('Ownership test','Assisted demo')); DELETE FROM Referral WHERE patientLabel IN ('Ownership test','Assisted demo'); DELETE FROM User WHERE email LIKE '%@test.local'; DELETE FROM FacilityServiceStatus WHERE facilityId='public-health-centre-west-mambalam' AND service='PRIMARY_CARE';");await new Promise<void>(resolve=>server.close(()=>resolve()));}});
