import assert from "node:assert/strict";
import test from "node:test";
import cookieParser from "cookie-parser";
import express from "express";
import { createAuthRouter, type GoogleCredentialVerifier } from "./auth-routes.ts";
import { db, initializeDatabase } from "./db.ts";

type Result={status:number;data:any;cookie:string};
const credential="x".repeat(160);
async function withServer(verifier:GoogleCredentialVerifier,run:(call:(path:string,body?:unknown,cookie?:string)=>Promise<Result>)=>Promise<void>){const app=express();app.use(express.json());app.use(cookieParser());app.use("/api/auth",createAuthRouter(verifier));const server=app.listen(0),address=server.address();assert.ok(address&&typeof address==="object");const base=`http://127.0.0.1:${address.port}`,call=async(path:string,body?:unknown,cookie="")=>{const response=await fetch(`${base}${path}`,{method:body?"POST":"GET",headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined}),setCookie=response.headers.get("set-cookie")||"";return{status:response.status,data:await response.json().catch(()=>({})),cookie:setCookie.split(";")[0]||cookie};};try{await run(call);}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}}

test("Google auth rejects invalid verification and unverified email",async()=>{initializeDatabase();process.env.GOOGLE_CLIENT_ID="test-google-client";await withServer(async()=>{throw new Error("wrong audience")},async call=>assert.equal((await call("/api/auth/google",{credential})).status,401));await withServer(async()=>({sub:"sub-unverified",email:"unverified@example.test",emailVerified:false,name:"No"}),async call=>assert.equal((await call("/api/auth/google",{credential})).status,401));});
test("verified Google user is a citizen, persists a session, and is not duplicated",async()=>{initializeDatabase();process.env.GOOGLE_CLIENT_ID="test-google-client";const email=`google-${Date.now()}@example.test`,sub=`google-sub-${Date.now()}`,verifier:GoogleCredentialVerifier=async(_credential,audience)=>{assert.equal(audience,"test-google-client");return{sub,email,emailVerified:true,name:"Google Citizen"};};try{await withServer(verifier,async call=>{const first=await call("/api/auth/google",{credential});assert.equal(first.status,200);assert.equal(first.data.user.role,"CITIZEN");const me=await call("/api/auth/me",undefined,first.cookie);assert.equal(me.status,200);assert.equal(me.data.user.id,first.data.user.id);const second=await call("/api/auth/google",{credential});assert.equal(second.data.user.id,first.data.user.id);const count=db.prepare("SELECT count(*) count FROM User WHERE email=?").get(email) as {count:number};assert.equal(count.count,1);});}finally{db.prepare("DELETE FROM User WHERE email=?").run(email);}});
test("verified Google email links to an existing password account",async()=>{initializeDatabase();process.env.GOOGLE_CLIENT_ID="test-google-client";const email=`link-${Date.now()}@example.test`,createdAt=new Date().toISOString();db.prepare("INSERT INTO User (id,name,email,passwordHash,role,preferredLanguage,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)").run(`link-${Date.now()}`,"Local User",email,"existing-hash","CITIZEN","en",createdAt,createdAt);try{await withServer(async()=>({sub:`linked-sub-${Date.now()}`,email,emailVerified:true,name:"Verified Name"}),async call=>{const result=await call("/api/auth/google",{credential});assert.equal(result.status,200);const row=db.prepare("SELECT passwordHash,googleSub FROM User WHERE email=?").get(email) as {passwordHash:string;googleSub:string};assert.equal(row.passwordHash,"existing-hash");assert.ok(row.googleSub);});}finally{db.prepare("DELETE FROM User WHERE email=?").run(email);}});
