import "dotenv/config";
import bcrypt from "bcryptjs";
import cookieParser from "cookie-parser";
import cors from "cors";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import { pathToFileURL } from "node:url";
import { z } from "zod";
import { assessNeed, nextSafetyQuestion, routeFacilities, serviceCapacity, structuredToMessage, travelMinutes, type Assessment, type Service } from "@ruralcare/shared";
import { clearSession, issueSession, requireAuth, requireRole, type AuthRequest, type SessionUser } from "./auth.ts";
import { db, initializeDatabase } from "./db.ts";
import { facilityProvenance } from "./facility-directory.ts";
import { facilityProvider } from "./facility-provider.ts";
import { clinicalExtractionProvider } from "./clinical-extraction.ts";

export const app=express();
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors({origin:process.env.FRONTEND_ORIGIN||"http://localhost:5173",credentials:true}));
app.use(express.json({limit:"8mb"}));app.use(cookieParser());
const loginLimit=rateLimit({windowMs:600000,limit:20,standardHeaders:true,legacyHeaders:false,message:{error:"Too many sign-in attempts. Please wait and try again."}});
const roles=z.enum(["CITIZEN","ASHA","STAFF"]),services=z.enum(["PRIMARY_CARE","MATERNITY","CHILD_HEALTH","EMERGENCY","TELECONSULT"]),statuses=z.enum(["CREATED","ACCEPTED","ARRIVED","FOLLOW_UP_DUE","COMPLETED"]);
const now=()=>new Date().toISOString(),stageLabel=(stage:string)=>stage==="FOLLOW_UP_DUE"?"Follow-up due":stage.slice(0,1)+stage.slice(1).toLowerCase(),serviceLabel=(service:string)=>({PRIMARY_CARE:"Primary Care",MATERNITY:"Maternal Care",CHILD_HEALTH:"Child Health",EMERGENCY:"Emergency Care",TELECONSULT:"Teleconsultation"} as Record<string,string>)[service]||service;
const safeUser=(row:Record<string,unknown>):SessionUser=>({id:String(row.id),name:String(row.name),email:row.email?String(row.email):null,phone:row.phone?String(row.phone):null,role:roles.parse(row.role),facilityId:row.facilityId?String(row.facilityId):null});
const referralRow=(id:string)=>db.prepare("SELECT * FROM Referral WHERE id=? OR demoId=? OR clientId=?").get(id,id,id) as Record<string,unknown>|undefined;
function canAccess(user:SessionUser,referral:Record<string,unknown>){if(user.role==="CITIZEN")return referral.ownerUserId===user.id;if(user.role==="ASHA")return referral.createdByUserId===user.id||referral.assistedByUserId===user.id;return Boolean(user.facilityId)&&referral.selectedFacilityId===user.facilityId;}
function addGap(input:{dedupeKey:string;requestId?:string;referralId?:string;requiredService:string;facilityId?:string;eventType:string}){db.prepare("INSERT OR IGNORE INTO ServiceGapEvent (id,dedupeKey,requestId,referralId,requiredService,district,facilityId,eventType,timestamp) VALUES (?,?,?,?,?,?,?,?,?)").run(crypto.randomUUID(),input.dedupeKey,input.requestId||null,input.referralId||null,input.requiredService,"Chennai demo region",input.facilityId||null,input.eventType,now());}
function addStatus(referralId:string,fromStatus:string|null,toStatus:string,actor:SessionUser|{id?:string;role:"SYSTEM"},action:string){db.prepare("INSERT INTO ReferralStatusEvent (id,referralId,fromStatus,toStatus,timestamp,actorType,actorUserId,action) VALUES (?,?,?,?,?,?,?,?)").run(crypto.randomUUID(),referralId,fromStatus,toStatus,now(),actor.role,actor.id||null,action);}
function assessmentFor(service:Service,urgency:string):Assessment{return {urgency:urgency as Assessment["urgency"],service,symptoms:["Non-diagnostic referral summary"],duration:"Recorded in referral",explanation:"Recalculation from the confirmed referral service.",nextAction:"Use the updated public-care pathway.",language:"en",redFlags:[],extraction:{ageGroup:service==="CHILD_HEALTH"?"CHILD":"ADULT",symptoms:[],duration:"Recorded",childFever:false,canDrink:null,repeatedVomiting:null,convulsions:null,consciousnessChange:null,breathingDifficulty:null,stiffNeck:null,severeBleeding:null,pregnancy:service==="MATERNITY"},triggeredRules:[],missingInformation:[]};}
function referralDetail(id:string,user:SessionUser){const referral=referralRow(id);if(!referral||!canAccess(user,referral))return null;return {referral,history:db.prepare("SELECT id,referralId,fromStatus,toStatus,timestamp,actorType,action FROM ReferralStatusEvent WHERE referralId=? ORDER BY timestamp").all(String(referral.id)),followUps:db.prepare("SELECT id,referralId,outcome,note,timestamp,sourceMode FROM FollowUpOutcome WHERE referralId=? ORDER BY timestamp DESC").all(String(referral.id))};}
function scopedReferrals(user:SessionUser){if(user.role==="CITIZEN")return db.prepare("SELECT * FROM Referral WHERE ownerUserId=? ORDER BY updatedAt DESC,createdAt DESC").all(user.id) as Array<Record<string,unknown>>;if(user.role==="ASHA")return db.prepare("SELECT * FROM Referral WHERE createdByUserId=? OR assistedByUserId=? ORDER BY updatedAt DESC,createdAt DESC").all(user.id,user.id) as Array<Record<string,unknown>>;return db.prepare("SELECT * FROM Referral WHERE selectedFacilityId=? ORDER BY updatedAt DESC,createdAt DESC").all(user.facilityId||"") as Array<Record<string,unknown>>;}
function coordination(user:SessionUser){const referrals=scopedReferrals(user),gaps=db.prepare("SELECT requiredService,facilityId,eventType,timestamp FROM ServiceGapEvent WHERE facilityId=? OR facilityId IN (SELECT name FROM Facility WHERE id=?) ORDER BY timestamp DESC").all(user.facilityId||"",user.facilityId||"") as Array<Record<string,unknown>>;const cases=referrals.map(item=>({id:item.id,demoId:item.demoId||`RCC-${String(item.id).slice(-4).toUpperCase()}`,careNeed:item.careNeed||serviceLabel(String(item.service)),service:item.service,urgency:item.urgency,facility:item.destinationFacility,sourceMode:item.sourceMode,rerouted:Boolean(item.rerouted),rerouteStatus:item.rerouteStatus,recommendedFacility:item.recommendedFacility,stage:stageLabel(String(item.status||"CREATED")),status:item.status||"CREATED",followUpDue:item.followUpDue,updatedAt:item.updatedAt||item.createdAt}));const taxonomy=["PRIMARY_CARE","CHILD_HEALTH","MATERNITY","EMERGENCY"],serviceAccess=taxonomy.map(service=>({service:serviceLabel(service),requests:cases.filter(item=>item.service===service).length,reroutes:cases.filter(item=>item.service===service&&item.rerouted).length,accessGaps:gaps.filter(item=>item.requiredService===service).length}));const gapGroups=Object.values(gaps.reduce<Record<string,{service:string;facility:string;reason:string;count:number}>>((acc,item)=>{const key=`${String(item.requiredService)}|${String(item.facilityId||"—")}|${String(item.eventType)}`;const current=acc[key]??{service:serviceLabel(String(item.requiredService)),facility:String(item.facilityId||"—"),reason:String(item.eventType).replaceAll("_"," "),count:0};current.count+=1;acc[key]=current;return acc;},{}));return {cases,totals:{incoming:cases.length,urgent:cases.filter(item=>item.urgency!=="ROUTINE").length,pending:cases.filter(item=>["CREATED","ACCEPTED"].includes(String(item.status))).length,followups:cases.filter(item=>item.status==="FOLLOW_UP_DUE").length,rerouted:cases.filter(item=>item.rerouted).length,serviceGaps:gaps.length},demand:serviceAccess.map(item=>({service:item.service,count:item.requests})),serviceAccess,recentGaps:gapGroups.slice(0,8),capacity:db.prepare("SELECT * FROM FacilityServiceStatus WHERE facilityId=? ORDER BY updatedAt DESC").all(user.facilityId||""),activity:cases.slice(0,6).map(item=>({demoId:item.demoId,stage:item.stage,careNeed:item.careNeed,facility:item.facility,updatedAt:item.updatedAt}))};}

app.get("/api/health",(_req,res)=>res.json({ok:true,mode:"synthetic-prototype"}));
app.post("/api/auth/register",loginLimit,async(req,res)=>{const parsed=z.object({name:z.string().trim().min(2).max(60),email:z.string().trim().email().optional(),phone:z.string().trim().regex(/^\+?[0-9]{10,15}$/).optional(),password:z.string().min(8).max(72),confirmPassword:z.string().min(8).max(72)}).refine(data=>data.email||data.phone,{message:"Email or phone is required"}).refine(data=>data.password===data.confirmPassword,{message:"Passwords do not match"}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message||"Invalid registration"});const duplicate=db.prepare("SELECT id FROM User WHERE email=? OR phone=?").get(parsed.data.email||"",parsed.data.phone||"");if(duplicate)return res.status(409).json({error:"An account already exists for that email or phone."});const id=crypto.randomUUID(),timestamp=now(),hash=await bcrypt.hash(parsed.data.password,12);db.prepare("INSERT INTO User (id,name,email,phone,passwordHash,role,facilityId,createdAt,updatedAt) VALUES (?,?,?,?,?,'CITIZEN',NULL,?,?)").run(id,parsed.data.name,parsed.data.email?.toLowerCase()||null,parsed.data.phone||null,hash,timestamp,timestamp);const user=safeUser(db.prepare("SELECT * FROM User WHERE id=?").get(id) as Record<string,unknown>);issueSession(res,user);res.status(201).json({user});});
app.post("/api/auth/login",loginLimit,async(req,res)=>{const parsed=z.object({identifier:z.string().trim().min(3).max(120),password:z.string().min(1).max(72)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Enter your email/phone and password."});const row=db.prepare("SELECT * FROM User WHERE lower(email)=lower(?) OR phone=?").get(parsed.data.identifier,parsed.data.identifier) as Record<string,unknown>|undefined;if(!row||!await bcrypt.compare(parsed.data.password,String(row.passwordHash)))return res.status(401).json({error:"Email/phone or password is incorrect."});const user=safeUser(row);issueSession(res,user);res.json({user});});
app.post("/api/auth/logout",(_req,res)=>{clearSession(res);res.json({ok:true});});
app.get("/api/auth/me",requireAuth,(req:AuthRequest,res)=>res.json({user:req.user}));
app.use("/api",requireAuth);

app.get("/api/facility-data",(_req,res)=>res.json({...facilityProvenance(),adapter:"ImportedGovernmentFacilityProvider"}));
app.post("/api/transcribe",async(req:AuthRequest,res)=>{const parsed=z.object({audioBase64:z.string().min(100).max(7_000_000),mimeType:z.string().max(80),language:z.enum(["ta","en"]).default("ta")}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"A short audio recording is required."});if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:"Tamil audio transcription is not configured. Add OPENAI_API_KEY to the root .env file and restart the app."});try{const audio=Buffer.from(parsed.data.audioBase64,"base64");if(audio.byteLength>5_000_000)return res.status(413).json({error:"Recording is too large. Please keep it under 15 seconds."});const extension=parsed.data.mimeType.includes("ogg")?"ogg":parsed.data.mimeType.includes("mp4")?"m4a":"webm",form=new FormData();form.append("file",new Blob([audio],{type:parsed.data.mimeType}),`ruralcare-${Date.now()}.${extension}`);form.append("model","whisper-1");form.append("language",parsed.data.language);form.append("response_format","json");const response=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:form}),result=await response.json() as {text?:string;error?:{message?:string}};if(!response.ok||!result.text?.trim())return res.status(502).json({error:result.error?.message||"Tamil transcription did not return text."});res.json({text:result.text.trim(),language:parsed.data.language,source:"CLOUD_AUDIO_TRANSCRIPTION",audioStored:false});}catch{return res.status(502).json({error:"Tamil transcription service could not be reached."});}});
app.post("/api/triage",(req,res)=>{const parsed=z.object({message:z.string().trim().min(2).max(1200)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Please enter a short description of the health need."});res.json({assessment:assessNeed(parsed.data.message),source:"validated-local-extraction-and-deterministic-rules"});});
app.post("/api/intake/extract",async(req,res)=>{const parsed=z.object({rawText:z.string().trim().min(2).max(1200),preferredResponseLanguage:z.enum(["en","ta"])}).strict().safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Please enter a short description of the health need."});const result=await clinicalExtractionProvider.extract(parsed.data.rawText,parsed.data.preferredResponseLanguage),assessment=assessNeed(structuredToMessage(result.structured)),nextQuestion=nextSafetyQuestion(result.structured,[],Number(process.env.MAX_ADAPTIVE_QUESTIONS||5),assessment.urgency==="EMERGENCY");res.json({...result,assessment,nextQuestion,decisionSource:"DETERMINISTIC_TRIAGE_RULES"});});
app.post("/api/routing",(req,res)=>{const parsed=z.object({message:z.string().trim().min(2).max(1200),requestId:z.string().trim().max(80).optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"A short care need is required for routing."});const assessment=assessNeed(parsed.data.message);if(assessment.urgency==="INSUFFICIENT_INFORMATION")return res.status(422).json({assessment,error:"More safety information is needed before facility routing."});const requestId=parsed.data.requestId||crypto.randomUUID(),decision=routeFacilities(facilityProvider.list(),assessment,requestId);if(!decision.selectedFacilityId)addGap({dedupeKey:`route:${requestId}:${decision.candidates.length?"all-unavailable":"no-match"}`,requestId,requiredService:decision.plan.requiredService,eventType:decision.candidates.length?"ALL_MATCHES_UNAVAILABLE":"NO_SUITABLE_FACILITY"});res.json({assessment,decision});});
app.get("/api/facilities",(req,res)=>{const service=services.catch("PRIMARY_CARE").parse(req.query.service),facilities=facilityProvider.list().filter(f=>f.services.includes(service));res.json({candidates:facilities.map(f=>({...f,travelMinutes:travelMinutes(f),serviceCapacity:serviceCapacity(f,service),availabilitySource:"SIMULATED_FOR_PROTOTYPE"})),dataLabel:"Official identity/location where sourced; prototype availability is not live government data"});});

app.get("/api/capacity",requireRole("STAFF"),(req:AuthRequest,res)=>res.json({facilities:facilityProvider.list().filter(item=>item.id===req.user?.facilityId),source:"SIMULATED_FOR_PROTOTYPE"}));
app.put("/api/capacity/:facilityId/:service",requireRole("STAFF"),(req:AuthRequest,res)=>{if(req.user?.facilityId!==req.params.facilityId)return res.status(403).json({error:"Staff can only change capacity for their assigned facility."});const parsed=z.object({availability:z.enum(["AVAILABLE","LIMITED","UNAVAILABLE"])}).safeParse(req.body),service=services.safeParse(req.params.service);if(!parsed.success||!service.success)return res.status(400).json({error:"Invalid prototype capacity update."});const facility=facilityProvider.list().find(item=>item.id===req.params.facilityId);if(!facility)return res.status(404).json({error:"Facility not found."});const timestamp=now();db.prepare("INSERT INTO FacilityServiceStatus (id,facilityId,service,availability,updatedAt,updatedBy,source) VALUES (?,?,?,?,?,?,?) ON CONFLICT(facilityId,service) DO UPDATE SET availability=excluded.availability,updatedAt=excluded.updatedAt,updatedBy=excluded.updatedBy,source=excluded.source").run(crypto.randomUUID(),facility.id,service.data,parsed.data.availability,timestamp,req.user.id,"SIMULATED_FOR_PROTOTYPE");const recommendations=[];if(parsed.data.availability==="UNAVAILABLE"){const affected=db.prepare("SELECT * FROM Referral WHERE selectedFacilityId=? AND service=? AND status!='COMPLETED'").all(facility.id,service.data) as Array<Record<string,unknown>>;for(const referral of affected){const decision=routeFacilities(facilityProvider.list(),assessmentFor(service.data,String(referral.urgency)),String(referral.requestId||referral.id)),next=decision.candidates.find(item=>item.id===decision.selectedFacilityId&&item.id!==facility.id);if(next){db.prepare("UPDATE Referral SET rerouted=1,previousFacility=COALESCE(previousFacility,destinationFacility),previousFacilityId=COALESCE(previousFacilityId,selectedFacilityId),rerouteStatus='REROUTE_RECOMMENDED',recommendedFacility=?,recommendedFacilityId=?,rerouteTimestamp=?,routingExplanation=?,updatedAt=? WHERE id=?").run(next.name,next.id,timestamp,decision.explanation,timestamp,String(referral.id));addStatus(String(referral.id),String(referral.status),String(referral.status),{role:"SYSTEM"},"REROUTE_RECOMMENDED");recommendations.push({referralId:String(referral.id),newFacility:next.name});}}}res.json({facilityId:facility.id,service:service.data,availability:parsed.data.availability,source:"SIMULATED_FOR_PROTOTYPE",recommendations});});

app.post("/api/referrals",requireRole("CITIZEN","ASHA"),(req:AuthRequest,res)=>{const parsed=z.object({clientId:z.string().uuid().optional(),patientLabel:z.string().trim().min(1).max(40),sourceFacility:z.string().max(120),destinationFacility:z.string().max(160),selectedFacilityId:z.string().min(2).max(100),service:services,urgency:z.enum(["EMERGENCY","URGENT","ROUTINE","INSUFFICIENT_INFORMATION"]),nextAction:z.string().max(240),careNeed:z.string().max(160).optional(),requestId:z.string().max(80).optional(),sourceMode:z.enum(["CITIZEN","ASHA_ASSISTED"]),selectedFacilityType:z.string().max(40).optional(),routingExplanation:z.string().max(500).optional(),rerouted:z.boolean().optional(),previousFacility:z.string().max(160).optional(),routingAudit:z.record(z.unknown()).optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Referral details are incomplete."});if((req.user?.role==="CITIZEN"&&parsed.data.sourceMode!=="CITIZEN")||(req.user?.role==="ASHA"&&parsed.data.sourceMode!=="ASHA_ASSISTED"))return res.status(403).json({error:"Referral source mode must match the signed-in role."});if(!facilityProvider.list().some(item=>item.id===parsed.data.selectedFacilityId&&item.name===parsed.data.destinationFacility))return res.status(400).json({error:"Selected public facility is invalid."});if(parsed.data.clientId){const existing=referralRow(parsed.data.clientId);if(existing){if(!canAccess(req.user!,existing))return res.status(403).json({error:"You do not have access to this referral."});return res.json({referral:existing,idempotent:true});}}const createdAt=now(),id=crypto.randomUUID(),demoId=`RCC-${Math.floor(1000+Math.random()*9000)}`,owner=req.user?.role==="CITIZEN"?req.user.id:null,assisted=req.user?.role==="ASHA"?req.user.id:null;db.prepare("INSERT INTO Referral (id,clientId,patientLabel,sourceFacility,destinationFacility,selectedFacilityId,service,urgency,status,nextAction,createdAt,demoId,careNeed,followUpDue,updatedAt,requestId,sourceMode,selectedFacilityType,routingExplanation,rerouted,previousFacility,routingAudit,ownerUserId,createdByUserId,assistedByUserId) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,parsed.data.clientId||null,parsed.data.patientLabel,parsed.data.sourceFacility,parsed.data.destinationFacility,parsed.data.selectedFacilityId,parsed.data.service,parsed.data.urgency,"CREATED",parsed.data.nextAction,createdAt,demoId,parsed.data.careNeed||serviceLabel(parsed.data.service),new Date(Date.now()+86400000).toISOString(),createdAt,parsed.data.requestId||null,parsed.data.sourceMode,parsed.data.selectedFacilityType||null,parsed.data.routingExplanation||null,Number(parsed.data.rerouted||false),parsed.data.previousFacility||null,JSON.stringify(parsed.data.routingAudit||{}),owner,req.user!.id,assisted);addStatus(id,null,"CREATED",req.user!,"REFERRAL_CREATED");res.status(201).json({referral:referralRow(id)});});
app.get("/api/referrals",(req:AuthRequest,res)=>res.json({referrals:scopedReferrals(req.user!)}));
app.get("/api/referrals/:id",(req:AuthRequest,res)=>{const detail=referralDetail(String(req.params.id),req.user!);if(!detail)return res.status(403).json({error:"You do not have access to this referral."});res.json(detail);});
const transitions:Record<string,string[]>={CREATED:["ACCEPTED"],ACCEPTED:["ARRIVED"],ARRIVED:["FOLLOW_UP_DUE","COMPLETED"],FOLLOW_UP_DUE:["COMPLETED"],COMPLETED:[]};
app.patch("/api/referrals/:id",requireRole("STAFF"),(req:AuthRequest,res)=>{const parsed=z.object({status:statuses}).safeParse(req.body),current=referralRow(String(req.params.id));if(!parsed.success)return res.status(400).json({error:"Invalid status."});if(!current||!canAccess(req.user!,current))return res.status(403).json({error:"Staff can only update referrals assigned to their facility."});if(!transitions[String(current.status)]?.includes(parsed.data.status))return res.status(409).json({error:`Invalid referral transition from ${current.status} to ${parsed.data.status}.`});db.prepare("UPDATE Referral SET status=?,updatedAt=? WHERE id=?").run(parsed.data.status,now(),String(current.id));addStatus(String(current.id),String(current.status),parsed.data.status,req.user!,"STATUS_UPDATED");res.json(referralDetail(String(current.id),req.user!));});
app.post("/api/referrals/:id/reroute/confirm",requireRole("CITIZEN","ASHA"),(req:AuthRequest,res)=>{const current=referralRow(String(req.params.id));if(!current||!canAccess(req.user!,current))return res.status(403).json({error:"You do not have access to this referral."});if(!current.recommendedFacility||!current.recommendedFacilityId)return res.status(404).json({error:"No reroute recommendation found."});db.prepare("UPDATE Referral SET destinationFacility=recommendedFacility,selectedFacilityId=recommendedFacilityId,rerouteStatus='REROUTE_CONFIRMED',updatedAt=? WHERE id=?").run(now(),String(current.id));addStatus(String(current.id),String(current.status),String(current.status),req.user!,"REROUTE_CONFIRMED");res.json(referralDetail(String(current.id),req.user!));});
app.post("/api/referrals/:id/follow-up",requireRole("CITIZEN","ASHA"),(req:AuthRequest,res)=>{const parsed=z.object({clientId:z.string().uuid(),outcome:z.enum(["CARE_REACHED","COULD_NOT_REACH","SERVICE_NOT_AVAILABLE","FOLLOW_UP_NEEDED","OTHER_ACCESS_PROBLEM"]),note:z.string().max(180).optional(),sourceMode:z.enum(["CITIZEN","ASHA_ASSISTED"])}).safeParse(req.body),current=referralRow(String(req.params.id));if(!parsed.success)return res.status(400).json({error:"Invalid follow-up."});if(!current||!canAccess(req.user!,current))return res.status(403).json({error:"You do not have access to this referral."});const existing=db.prepare("SELECT id,referralId,outcome,note,timestamp,sourceMode FROM FollowUpOutcome WHERE clientId=?").get(parsed.data.clientId);if(existing)return res.json({followUp:existing,idempotent:true});const id=crypto.randomUUID(),timestamp=now(),referralId=String(current.id);db.prepare("INSERT INTO FollowUpOutcome (id,clientId,referralId,outcome,note,timestamp,sourceMode) VALUES (?,?,?,?,?,?,?)").run(id,parsed.data.clientId,referralId,parsed.data.outcome,parsed.data.note||null,timestamp,parsed.data.sourceMode);const target=parsed.data.outcome==="CARE_REACHED"&&["ARRIVED","FOLLOW_UP_DUE"].includes(String(current.status))?"COMPLETED":parsed.data.outcome==="FOLLOW_UP_NEEDED"&&current.status==="ARRIVED"?"FOLLOW_UP_DUE":String(current.status);if(target!==current.status){db.prepare("UPDATE Referral SET status=?,updatedAt=? WHERE id=?").run(target,timestamp,referralId);addStatus(referralId,String(current.status),target,req.user!,"FOLLOW_UP_STATUS");}if(parsed.data.outcome==="SERVICE_NOT_AVAILABLE")addGap({dedupeKey:`followup:${parsed.data.clientId}`,requestId:String(current.requestId||""),referralId,requiredService:String(current.service),facilityId:String(current.selectedFacilityId||""),eventType:"SERVICE_REPORTED_UNAVAILABLE"});if(parsed.data.outcome==="COULD_NOT_REACH")addGap({dedupeKey:`followup:${parsed.data.clientId}`,requestId:String(current.requestId||""),referralId,requiredService:String(current.service),facilityId:String(current.selectedFacilityId||""),eventType:"COULD_NOT_REACH_FACILITY"});res.status(201).json({followUp:db.prepare("SELECT id,referralId,outcome,note,timestamp,sourceMode FROM FollowUpOutcome WHERE id=?").get(id),referral:referralDetail(referralId,req.user!)});});
app.get("/api/coordination",requireRole("STAFF"),(req:AuthRequest,res)=>res.json(coordination(req.user!)));app.get("/api/dashboard",requireRole("STAFF"),(req:AuthRequest,res)=>res.json(coordination(req.user!)));

export function startServer(port=Number(process.env.PORT||8787)){initializeDatabase();return app.listen(port,()=>console.log(`RuralCare API ready at http://localhost:${port}`));}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)startServer();
