import "dotenv/config";
import cors from "cors";
import express from "express";
import { z } from "zod";
import { assessNeed, routeFacilities, serviceCapacity, travelMinutes, type Assessment, type Facility, type Service } from "@ruralcare/shared";
import { db, initializeDatabase } from "./db.ts";
import { facilityProvenance } from "./facility-directory.ts";
import { facilityProvider } from "./facility-provider.ts";

const app=express(); app.use(cors()); app.use(express.json({limit:"100kb"}));
const services=z.enum(["PRIMARY_CARE","MATERNITY","CHILD_HEALTH","EMERGENCY","TELECONSULT"]);
const statuses=z.enum(["CREATED","ACCEPTED","ARRIVED","FOLLOW_UP_DUE","COMPLETED"]);
const now=()=>new Date().toISOString();
const stageLabel=(stage:string)=>stage==="FOLLOW_UP_DUE"?"Follow-up due":stage.slice(0,1)+stage.slice(1).toLowerCase();
const serviceLabel=(service:string)=>({PRIMARY_CARE:"Primary Care",MATERNITY:"Maternal Care",CHILD_HEALTH:"Child Health",EMERGENCY:"Emergency Care",TELECONSULT:"Teleconsultation"} as Record<string,string>)[service]||service;
function addGap(input:{dedupeKey:string;requestId?:string;referralId?:string;requiredService:string;facilityId?:string;eventType:string}){db.prepare("INSERT OR IGNORE INTO ServiceGapEvent (id,dedupeKey,requestId,referralId,requiredService,district,facilityId,eventType,timestamp) VALUES (?,?,?,?,?,?,?,?,?)").run(crypto.randomUUID(),input.dedupeKey,input.requestId||null,input.referralId||null,input.requiredService,"Chennai demo region",input.facilityId||null,input.eventType,now());}
function addStatus(referralId:string,fromStatus:string|null,toStatus:string,actorType:string){db.prepare("INSERT INTO ReferralStatusEvent (id,referralId,fromStatus,toStatus,timestamp,actorType) VALUES (?,?,?,?,?,?)").run(crypto.randomUUID(),referralId,fromStatus,toStatus,now(),actorType);}
function assessmentFor(service:Service,urgency:string):Assessment{return {urgency:urgency as Assessment["urgency"],service,symptoms:["Non-diagnostic referral summary"],duration:"Recorded in referral",explanation:"Recalculation from the confirmed referral service.",nextAction:"Use the updated public-care pathway.",language:"en",redFlags:[],extraction:{ageGroup:service==="CHILD_HEALTH"?"CHILD":"ADULT",symptoms:[],duration:"Recorded",childFever:false,canDrink:null,repeatedVomiting:null,convulsions:null,consciousnessChange:null,breathingDifficulty:null,stiffNeck:null,severeBleeding:null,pregnancy:service==="MATERNITY"},triggeredRules:[],missingInformation:[]};}
function referralDetail(id:string){const referral=db.prepare("SELECT * FROM Referral WHERE id=? OR demoId=? OR clientId=?").get(id,id,id) as Record<string,unknown>|undefined;if(!referral)return null;return {referral,history:db.prepare("SELECT * FROM ReferralStatusEvent WHERE referralId=? ORDER BY timestamp").all(String(referral.id)),followUps:db.prepare("SELECT * FROM FollowUpOutcome WHERE referralId=? ORDER BY timestamp DESC").all(String(referral.id))};}
function coordination(){
  const referrals=db.prepare("SELECT * FROM Referral ORDER BY updatedAt DESC,createdAt DESC").all() as Array<Record<string,unknown>>, gaps=db.prepare("SELECT * FROM ServiceGapEvent ORDER BY timestamp DESC").all() as Array<Record<string,unknown>>;
  const cases=referrals.map(item=>({id:item.id,demoId:item.demoId||`RCC-${String(item.id).slice(-4).toUpperCase()}`,careNeed:item.careNeed||serviceLabel(String(item.service)),service:item.service,urgency:item.urgency,facility:item.destinationFacility,sourceMode:item.sourceMode||"ASHA_ASSISTED",rerouted:Boolean(item.rerouted),rerouteStatus:item.rerouteStatus,recommendedFacility:item.recommendedFacility,stage:stageLabel(String(item.status||"CREATED")),status:item.status||"CREATED",followUpDue:item.followUpDue,updatedAt:item.updatedAt||item.createdAt}));
  const taxonomy=["PRIMARY_CARE","CHILD_HEALTH","MATERNITY","EMERGENCY"];
  const serviceAccess=taxonomy.map(service=>({service:serviceLabel(service),requests:cases.filter(item=>item.service===service).length,reroutes:cases.filter(item=>item.service===service&&item.rerouted).length,accessGaps:gaps.filter(item=>item.requiredService===service).length}));
  const gapGroups=Object.values(gaps.reduce<Record<string,{service:string;facility:string;reason:string;count:number}>>((acc,item)=>{const key=`${String(item.requiredService)}|${String(item.facilityId||"—")}|${String(item.eventType)}`;const current=acc[key]??{service:serviceLabel(String(item.requiredService)),facility:String(item.facilityId||"—"),reason:String(item.eventType).replaceAll("_"," "),count:0};current.count+=1;acc[key]=current;return acc;},{}));
  return {cases,totals:{incoming:cases.length,urgent:cases.filter(item=>item.urgency!=="ROUTINE").length,pending:cases.filter(item=>["CREATED","ACCEPTED"].includes(String(item.status))).length,followups:cases.filter(item=>item.status==="FOLLOW_UP_DUE").length,rerouted:cases.filter(item=>item.rerouted).length,serviceGaps:gaps.length},demand:serviceAccess.map(item=>({service:item.service,count:item.requests})),serviceAccess,recentGaps:gapGroups.slice(0,8),capacity:db.prepare("SELECT * FROM FacilityServiceStatus ORDER BY updatedAt DESC").all(),activity:cases.slice(0,6).map(item=>({demoId:item.demoId,stage:item.stage,careNeed:item.careNeed,facility:item.facility,updatedAt:item.updatedAt}))};
}

app.get("/api/health",(_req,res)=>res.json({ok:true,mode:"synthetic-prototype"}));
app.get("/api/facility-data",(_req,res)=>res.json({...facilityProvenance(),adapter:"ImportedGovernmentFacilityProvider"}));
app.post("/api/triage",(req,res)=>{const parsed=z.object({message:z.string().trim().min(2).max(1200)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Please enter a short description of the health need."});res.json({assessment:assessNeed(parsed.data.message),source:"validated-local-extraction-and-deterministic-rules"});});
app.post("/api/routing",(req,res)=>{const parsed=z.object({message:z.string().trim().min(2).max(1200),requestId:z.string().trim().max(80).optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"A short care need is required for routing."});const assessment=assessNeed(parsed.data.message);if(assessment.urgency==="INSUFFICIENT_INFORMATION")return res.status(422).json({assessment,error:"More safety information is needed before facility routing."});const requestId=parsed.data.requestId||crypto.randomUUID(),decision=routeFacilities(facilityProvider.list(),assessment,requestId);if(!decision.selectedFacilityId)addGap({dedupeKey:`route:${requestId}:${decision.candidates.length?"all-unavailable":"no-match"}`,requestId,requiredService:decision.plan.requiredService,eventType:decision.candidates.length?"ALL_MATCHES_UNAVAILABLE":"NO_SUITABLE_FACILITY"});res.json({assessment,decision});});
app.get("/api/facilities",(req,res)=>{const service=services.catch("PRIMARY_CARE").parse(req.query.service);const facilities=facilityProvider.list().filter(f=>f.services.includes(service));res.json({candidates:facilities.map(f=>({...f,travelMinutes:travelMinutes(f),serviceCapacity:serviceCapacity(f,service),availabilitySource:"SIMULATED_FOR_PROTOTYPE"})),dataLabel:"Official identity/location where sourced; prototype availability is not live government data"});});
app.get("/api/capacity",(_req,res)=>res.json({facilities:facilityProvider.list(),source:"SIMULATED_FOR_PROTOTYPE"}));
app.put("/api/capacity/:facilityId/:service",(req,res)=>{const parsed=z.object({availability:z.enum(["AVAILABLE","LIMITED","UNAVAILABLE"])}).safeParse(req.body),service=services.safeParse(req.params.service);if(!parsed.success||!service.success)return res.status(400).json({error:"Invalid prototype capacity update."});const facility=facilityProvider.list().find(item=>item.id===req.params.facilityId);if(!facility)return res.status(404).json({error:"Facility not found."});const timestamp=now();db.prepare("INSERT INTO FacilityServiceStatus (id,facilityId,service,availability,updatedAt,updatedBy,source) VALUES (?,?,?,?,?,?,?) ON CONFLICT(facilityId,service) DO UPDATE SET availability=excluded.availability,updatedAt=excluded.updatedAt,updatedBy=excluded.updatedBy,source=excluded.source").run(crypto.randomUUID(),facility.id,service.data,parsed.data.availability,timestamp,"DEMO_STAFF","SIMULATED_FOR_PROTOTYPE");const updatedFacilities=facilityProvider.list();const affected=db.prepare("SELECT * FROM Referral WHERE destinationFacility=? AND service=? AND status NOT IN ('COMPLETED')").all(facility.name,service.data) as Array<Record<string,unknown>>;const recommendations=[];if(parsed.data.availability==="UNAVAILABLE")for(const referral of affected){const decision=routeFacilities(updatedFacilities,assessmentFor(service.data,String(referral.urgency)),String(referral.requestId||referral.id));const next=decision.candidates.find(item=>item.id===decision.selectedFacilityId&&item.name!==facility.name);if(next){db.prepare("UPDATE Referral SET rerouted=1,previousFacility=COALESCE(previousFacility,destinationFacility),rerouteStatus='REROUTE_RECOMMENDED',recommendedFacility=?,rerouteTimestamp=?,routingExplanation=?,updatedAt=? WHERE id=?").run(next.name,timestamp,decision.explanation,timestamp,String(referral.id));recommendations.push({referralId:String(referral.id),newFacility:next.name});}}res.json({facilityId:facility.id,service:service.data,availability:parsed.data.availability,source:"SIMULATED_FOR_PROTOTYPE",recommendations});});
app.post("/api/referrals",(req,res)=>{const parsed=z.object({clientId:z.string().uuid().optional(),patientLabel:z.string().trim().min(1).max(40),sourceFacility:z.string(),destinationFacility:z.string(),service:services,urgency:z.string(),nextAction:z.string().max(240),careNeed:z.string().max(160).optional(),requestId:z.string().max(80).optional(),sourceMode:z.enum(["CITIZEN","ASHA_ASSISTED"]),selectedFacilityType:z.string().max(40).optional(),routingExplanation:z.string().max(500).optional(),rerouted:z.boolean().optional(),previousFacility:z.string().max(160).optional(),routingAudit:z.record(z.unknown()).optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Referral details are incomplete."});if(parsed.data.clientId){const existing=db.prepare("SELECT * FROM Referral WHERE clientId=?").get(parsed.data.clientId);if(existing)return res.json({referral:existing,idempotent:true});}const createdAt=now(),id=crypto.randomUUID(),demoId=`RCC-${Math.floor(1000+Math.random()*9000)}`;db.prepare("INSERT INTO Referral (id,clientId,patientLabel,sourceFacility,destinationFacility,service,urgency,status,nextAction,createdAt,demoId,careNeed,followUpDue,updatedAt,requestId,sourceMode,selectedFacilityType,routingExplanation,rerouted,previousFacility,routingAudit) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,parsed.data.clientId||null,parsed.data.patientLabel,parsed.data.sourceFacility,parsed.data.destinationFacility,parsed.data.service,parsed.data.urgency,"CREATED",parsed.data.nextAction,createdAt,demoId,parsed.data.careNeed||serviceLabel(parsed.data.service),new Date(Date.now()+86400000).toISOString(),createdAt,parsed.data.requestId||null,parsed.data.sourceMode,parsed.data.selectedFacilityType||null,parsed.data.routingExplanation||null,Number(parsed.data.rerouted||false),parsed.data.previousFacility||null,JSON.stringify(parsed.data.routingAudit||{}));addStatus(id,null,"CREATED",parsed.data.sourceMode==="CITIZEN"?"CITIZEN":"ASHA");res.status(201).json({referral:db.prepare("SELECT * FROM Referral WHERE id=?").get(id)});});
app.get("/api/referrals",(_req,res)=>res.json({referrals:db.prepare("SELECT * FROM Referral ORDER BY createdAt DESC LIMIT 50").all()}));
app.get("/api/referrals/:id",(req,res)=>{const detail=referralDetail(req.params.id);if(!detail)return res.status(404).json({error:"Referral not found"});res.json(detail);});
app.patch("/api/referrals/:id",(req,res)=>{const parsed=z.object({status:statuses,actorType:z.enum(["CITIZEN","ASHA","STAFF","SYSTEM"]).default("STAFF")}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Invalid status"});const current=db.prepare("SELECT * FROM Referral WHERE id=?").get(req.params.id) as Record<string,unknown>|undefined;if(!current)return res.status(404).json({error:"Referral not found"});db.prepare("UPDATE Referral SET status=?,updatedAt=? WHERE id=?").run(parsed.data.status,now(),req.params.id);addStatus(req.params.id,String(current.status),parsed.data.status,parsed.data.actorType);res.json(referralDetail(req.params.id));});
app.post("/api/referrals/:id/reroute/confirm",(req,res)=>{const current=db.prepare("SELECT * FROM Referral WHERE id=?").get(req.params.id) as Record<string,unknown>|undefined;if(!current||!current.recommendedFacility)return res.status(404).json({error:"No reroute recommendation found"});db.prepare("UPDATE Referral SET destinationFacility=recommendedFacility,rerouteStatus='REROUTE_CONFIRMED',updatedAt=? WHERE id=?").run(now(),req.params.id);res.json(referralDetail(req.params.id));});
app.post("/api/referrals/:id/follow-up",(req,res)=>{const parsed=z.object({clientId:z.string().uuid(),outcome:z.enum(["CARE_REACHED","COULD_NOT_REACH","SERVICE_NOT_AVAILABLE","FOLLOW_UP_NEEDED","OTHER_ACCESS_PROBLEM"]),note:z.string().max(180).optional(),sourceMode:z.enum(["CITIZEN","ASHA_ASSISTED"])}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Invalid follow-up"});const detail=referralDetail(req.params.id);if(!detail)return res.status(404).json({error:"Referral not found"});const existing=db.prepare("SELECT * FROM FollowUpOutcome WHERE clientId=?").get(parsed.data.clientId);if(existing)return res.json({followUp:existing,idempotent:true});const id=crypto.randomUUID(),timestamp=now(),referralId=String(detail.referral.id);db.prepare("INSERT INTO FollowUpOutcome (id,clientId,referralId,outcome,note,timestamp,sourceMode) VALUES (?,?,?,?,?,?,?)").run(id,parsed.data.clientId,referralId,parsed.data.outcome,parsed.data.note||null,timestamp,parsed.data.sourceMode);const target=parsed.data.outcome==="CARE_REACHED"?"COMPLETED":parsed.data.outcome==="FOLLOW_UP_NEEDED"?"FOLLOW_UP_DUE":String(detail.referral.status);if(target!==detail.referral.status){db.prepare("UPDATE Referral SET status=?,updatedAt=? WHERE id=?").run(target,timestamp,referralId);addStatus(referralId,String(detail.referral.status),target,parsed.data.sourceMode==="CITIZEN"?"CITIZEN":"ASHA");}if(parsed.data.outcome==="SERVICE_NOT_AVAILABLE")addGap({dedupeKey:`followup:${parsed.data.clientId}`,requestId:String(detail.referral.requestId||""),referralId,requiredService:String(detail.referral.service),facilityId:String(detail.referral.destinationFacility),eventType:"SERVICE_REPORTED_UNAVAILABLE"});if(parsed.data.outcome==="COULD_NOT_REACH")addGap({dedupeKey:`followup:${parsed.data.clientId}`,requestId:String(detail.referral.requestId||""),referralId,requiredService:String(detail.referral.service),facilityId:String(detail.referral.destinationFacility),eventType:"COULD_NOT_REACH_FACILITY"});res.status(201).json({followUp:db.prepare("SELECT * FROM FollowUpOutcome WHERE id=?").get(id),referral:referralDetail(referralId)});});
app.get("/api/coordination",(_req,res)=>res.json(coordination())); app.get("/api/dashboard",(_req,res)=>res.json(coordination()));

const port=Number(process.env.PORT||8787); initializeDatabase(); app.listen(port,()=>console.log(`RuralCare API ready at http://localhost:${port}`));
